### ISSUE TITLE
Accumulo resources not properly closed

### ISSUE THREAD

**Issue by mteldridge** [locationtech/geotrellis#2089]
Anytime I run AccumuloLayerDeleter.delete(), I get the following warning stacktrace when the finalizers are run.  This is due to the fact that the batch deleter never gets closed.  It should be closed after deleter.delete() is called (or perhaps in a finally clause) in AccumuloLayerDeleter.scala.  This probably is an issue in the other AccumuloLayerManager methods as well.  

` 14:45:54.585 [Finalizer] WARN  org.apache.accumulo.core.client.impl.TabletServerBatchReader - TabletServerBatchReader not shutdown; did you forget to call close()?
java.lang.Throwable: null
	at org.apache.accumulo.core.client.impl.TabletServerBatchReader.<init>(TabletServerBatchReader.java:69)
	at org.apache.accumulo.core.client.impl.TabletServerBatchDeleter.<init>(TabletServerBatchDeleter.java:43)
	at org.apache.accumulo.core.client.impl.ConnectorImpl.createBatchDeleter(ConnectorImpl.java:114)
	at geotrellis.spark.io.accumulo.AccumuloLayerDeleter.delete(AccumuloLayerDeleter.scala:41)
	at geotrellis.spark.io.accumulo.AccumuloLayerManager.delete(AccumuloLayerManager.scala:36)
	at astraea.spark.ingest.IngestTest$$anonfun$3.apply$mcV$sp(IngestTest.scala:208)
	at astraea.spark.ingest.IngestTest$$anonfun$3.apply(IngestTest.scala:206)
	at astraea.spark.ingest.IngestTest$$anonfun$3.apply(IngestTest.scala:206)
	at org.scalatest.BeforeAndAfter$$anonfun$1.apply$mcV$sp(BeforeAndAfter.scala:219)
	at org.scalatest.Status$$anonfun$withAfterEffect$1.apply(Status.scala:379)
	at org.scalatest.Status$$anonfun$withAfterEffect$1.apply(Status.scala:375)
	at org.scalatest.SucceededStatus$.whenCompleted(Status.scala:454)
	at org.scalatest.Status$class.withAfterEffect(Status.scala:375)
	at org.scalatest.SucceededStatus$.withAfterEffect(Status.scala:426)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:216)
	at astraea.spark.ingest.IngestTest.runTest(IngestTest.scala:27)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
	at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
	at astraea.spark.ingest.IngestTest.org$scalatest$BeforeAndAfter$$super$run(IngestTest.scala:27)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:258)
	at astraea.spark.ingest.IngestTest.run(IngestTest.scala:27)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by pomadchin** [comment]
Hi! What Accunulo version do you use?

**Comment by mteldridge** [comment]
We are still on 1.6.6

**Comment by pomadchin** [comment]
Ok, I'll try to check it on 1.6, 1.7 to figure out where is the problem.
