### ISSUE TITLE
Read .csv of Points in GeoTrellis

### ISSUE THREAD

**Issue by MikeChenfu** [locationtech/geotrellis#2227]
Hello,

Is there any way to read csv files? I try some ways but they do not work. I really appreciate it if anyone can provide an example.

**Comment by echeipesh** [comment]
There is no dedicated CSV parsing in GeoTrellis. I would guess that you have lat,lng + attributes in CSV format, in which case you would need to read and parse them as a normal CSV file then map over the result to create either `Point` of `PointFeature` from the fields as makes sense for that file.

As a basic example
```scala
val sc: SparkContext = ???

val lines: RDD[String] = sc.textFile("data.csv")
val points: RDD[PointFeature[String]] = lines.map { line =>
  val fields = lines.split(",")
  val point = Point(x = fields(0).toDouble, y = fields(1).toDouble)
  PointFeature(point, fields(2))
}
```
Just as an example though, `split(",")` won't handle quoted field values correctly. 
In reality you would want to use a dedicated CSV parsing library.

**Comment by MikeChenfu** [comment]
Thank you so much. That's a good example for me .

**Comment by MikeChenfu** [comment]
I try this code and get an error "not found: type SparkContext". Should I import another library for that? Thanks.

**Comment by jpolchlo** [comment]
You might do well to start here: http://geotrellis.readthedocs.io/en/latest/

There are a number of tutorials that will help getting you up to speed.

**Comment by echeipesh** [comment]
Ah, thats my fault, I assumed that you were already working with spark. What is it that you're trying to do with GeoTrellis and CSV?

**Comment by MikeChenfu** [comment]
Thanks for your time. I want to use Geotrellis to read csv files and transfer it to Geotiff.

**Comment by echeipesh** [comment]
Sounds like it would be a nice example, what is actually in the files, points? And what are they supposed to look like on the GeoTiff ?

**Comment by MikeChenfu** [comment]
Yes, they are points, containing lat,lng and other attributes in CSV format.

**Comment by MikeChenfu** [comment]
I follow the guide "Using GeoTrellis with Apache Spark" and try loading csv file. It works to set up a sc.parallelize(Array(1,2,3)), but it cannot run `val lines: RDD[String] = sc.textFile("data.csv")`. Do you have any idea about this problem? Thanks.

**Comment by jpolchlo** [comment]
Sorry, but do you have more details on the error?  Can you post the exception message?

**Comment by MikeChenfu** [comment]
Thanks for your help. That's the part of details on the error.

`scala> val lines: RDD[String] = sc.textFile("test.csv")
17/06/07 11:24:35 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 144.5 KB, free 710.7 MB)
org.apache.spark.SparkException: Failed to register classes with Kryo

at org.apache.spark.serializer.KryoSerializer.newKryo(KryoSerializer.scala:129)
  at org.apache.spark.serializer.KryoSerializerInstance.borrowKryo(KryoSerializer.scala:274)
  at org.apache.spark.serializer.KryoSerializerInstance.<init>(KryoSerializer.scala:259)
  at org.apache.spark.serializer.KryoSerializer.newInstance(KryoSerializer.scala:175)
  at org.apache.spark.broadcast.TorrentBroadcast$.blockifyObject(TorrentBroadcast.scala:233)
  at org.apache.spark.broadcast.TorrentBroadcast.writeBlocks(TorrentBroadcast.scala:107)
  at org.apache.spark.broadcast.TorrentBroadcast.<init>(TorrentBroadcast.scala:86)
  at org.apache.spark.broadcast.TorrentBroadcastFactory.newBroadcast(TorrentBroadcastFactory.scala:34)
  at org.apache.spark.broadcast.BroadcastManager.newBroadcast(BroadcastManager.scala:56)
  at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1387)
  at org.apache.spark.SparkContext$$anonfun$hadoopFile$1.apply(SparkContext.scala:991)
  at org.apache.spark.SparkContext$$anonfun$hadoopFile$1.apply(SparkContext.scala:983)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.SparkContext.withScope(SparkContext.scala:679)
  at org.apache.spark.SparkContext.hadoopFile(SparkContext.scala:983)
  at org.apache.spark.SparkContext$$anonfun$textFile$1.apply(SparkContext.scala:799)
  at org.apache.spark.SparkContext$$anonfun$textFile$1.apply(SparkContext.scala:797)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
  at org.apache.spark.SparkContext.withScope(SparkContext.scala:679)
  at org.apache.spark.SparkContext.textFile(SparkContext.scala:797)
  ... 42 elided
Caused by: java.lang.IllegalArgumentException: Unable to create serializer "com.esotericsoftware.kryo.serializers.FieldSerializer" for class: geotrellis.spark.SpaceTimeKey
  at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.makeSerializer(ReflectionSerializerFactory.java:67)
  at com.esotericsoftware.kryo.factories.ReflectionSerializerFactory.makeSerializer(ReflectionSerializerFactory.java:45)
  at com.esotericsoftware.kryo.Kryo.newDefaultSerializer(Kryo.java:380)
  at com.twitter.chill.KryoBase.newDefaultSerializer(KryoBase.scala:50)
  at com.esotericsoftware.kryo.Kryo.getDefaultSerializer(Kryo.java:364)
  at com.esotericsoftware.kryo.Kryo.register(Kryo.java:394)
  at geotrellis.spark.io.kryo.KryoRegistrator.registerClasses(KryoRegistrator.scala:132)

`

**Comment by jpolchlo** [comment]
This sounds like the "spark.serializer" hasn't been set.  I'm not sure exactly how you've arrived at a scala console (was this from the `geotrellis-sbt-template` project, or from a `spark-shell`?), but the `SparkConf` object must have `.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")` called on it.  This _should not be required_ if you used `geotrellis.spark.util.SparkUtils.createSparkContext`, as it will add this to the SparkConf for you.  If you are using `spark-shell` then you must add `--conf spark.serializer=org.apache.spark.serializer.KryoSerializer` to the arguments to `spark-shell` in addition to specifying the `--jars` argument.  That last conf argument was not specified in the docs, so I'll fix that omission.

**Comment by MikeChenfu** [comment]
Thanks for your information. I access scala console from the `geotrellis-sbt-template`. When I added `.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")` to `SparkConf`, I got the same error. 
Here are my all of commands:

```
//access the console
./sbt
test:console

//read .csv file
val conf = new org.apache.spark.SparkConf()
conf.setMaster("local[*]").set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
implicit val sc = geotrellis.spark.util.SparkUtils.createSparkContext("Test console", conf)
val lines: RDD[String] = sc.textFile("test.csv")
```

**Comment by jpolchlo** [comment]
At this point, I don't have a ready solution, as this sequence of commands causes me no problems.  There are any number of system configurations that could be standing in your way, so I'm not entirely sure where to point you next. I should also mention that the `geotrellis/geotrellis` channel on `gitter.im` might be a better locale for addressing this issue.

**Comment by MikeChenfu** [comment]
Yes, I think it may be realted to my system configuration. I will check it. 
I am very interested in the Geotrellis work. I have some csv files and json files. I may meet a bottleneck on reading csv file but I will keep working on it. 
I think Geotrellis provides an I/O to read json files. I read the documents by the link  [](http://geotrellis.readthedocs.io/en/latest/), but I do not get it. I really appreciate it if you can provide me an example to read json file.

**Comment by MikeChenfu** [comment]
The document link is [http://geotrellis.readthedocs.io/en/latest/].

**Comment by MikeChenfu** [comment]
Yes, I think it may be realted to my system configuration. I will check it.
I am very interested in the Geotrellis work. I have some csv files and json files. I may meet a bottleneck on reading csv file but I will keep working on it.
I think Geotrellis provides an I/O to read json files. I read the documents by the link [,](http://geotrellis.readthedocs.io/en/latest/) but I do not get it. I really appreciate it if you can provide me an example to read json file.

**Comment by MikeChenfu** [comment]
Yes, I think it may be realted to my system configuration. I will check it.
I am very interested in the Geotrellis work. I have some csv files and json files. I may meet a bottleneck on reading csv file but I will keep working on it.
I think Geotrellis provides an I/O to read json files. I read the documents by the link  "http://geotrellis.readthedocs.io/en/latest/ ", but I do not get it. I really appreciate it if you can provide me an example to read json file.

**Comment by pomadchin** [comment]
hi @MikeChenfu ! It depends on how you want to read `json` file(s). However we don't provide IO for JSON (as well as for CSV) files (i guess you're talking about GeoJson), but we have GeoJson codecs (to encode geometry types into GeoJson, and to decode GeoJson into geometry types). See [this](http://geotrellis.readthedocs.io/en/latest/guide/vectors.html?highlight=GeoJson) docs link.

**Comment by echeipesh** [comment]
Seems like this issue was worked through. Please hit us up on `geotrellis/geotrellis` on `gitter.im` if there are more help is needed.
