### ISSUE TITLE
Cannot Create Gridbounds for Layer Ingest

### ISSUE THREAD

**Issue by notthatbreezy** [locationtech/geotrellis#2265]
In Raster Foundry we are trying to ingest some high resolution imagery, but have run into a problem where we cannot create `GridBounds` because of [this check](https://github.com/locationtech/geotrellis/blob/a00c35b928e96083188d91734252d66574e3b4a7/raster/src/main/scala/geotrellis/raster/GridBounds.scala#L78). The specific error we encountered is: `Cannot construct grid bounds of this size: 79047 x 91220`.

Two questions:
 - Is there a workaround or better way we can do an ingest into a GeoTrellis layer to avoid this? Currently we plan to [split the source data](https://github.com/azavea/raster-foundry/issues/2144) into separate GeoTrellis ingested layers to get around this problem.
 - Is it possible to relax this restriction and use `Long` instead of `Int` for size?

**Comment by echeipesh** [comment]
This appears to be a check for basic limitation, we can't hold more elements than `Int.MaxValue` in a single tile. This error check may be misplaced for that purpose. @lossyrob Was there another reason for it.

Ideally we can do a windowed ingest on a large file without triggering this error. Is it possible to get a stack trace and access to the file to try to analyze this further?

**Comment by notthatbreezy** [comment]
I'm not sure I can provide access to the file because it is sensitive/private - but I can see if I can put together something by upsampling a lower resolution raster.

Might take a bit to track down the stack trace, will see what I can do.

**Comment by fosskers** [comment]
Investigating this. I'll try to forge a giant image myself. Would it have to be a geotiff?

**Comment by jamesmcclain** [comment]
Perhaps a bigtiff?

**Comment by notthatbreezy** [comment]
It doesn't need to be a bigtiff, a compressed tiff of all `1` values with where width * height (in pixels) is greater than 2,147,483,647 should compress well.

**Comment by fosskers** [comment]
Alright, I've been able to reproduce this outside of RF. Naive input settings during ETL give the following on a 60k-by-60k geotiff:

```
java.lang.NegativeArraySizeException
    at scala.reflect.ManifestFactory$$anon$9.newArray(Manifest.scala:117)
    at scala.reflect.ManifestFactory$$anon$9.newArray(Manifest.scala:115)
    at scala.Array$.ofDim(Array.scala:218)
    at geotrellis.raster.IntArrayTile$.fill(IntArrayTile.scala:334)
    at geotrellis.raster.IntArrayTile$.empty(IntArrayTile.scala:302)
    at geotrellis.raster.ArrayTile$.empty(ArrayTile.scala:435)
    at geotrellis.raster.io.geotiff.GeoTiffTile.mutable(GeoTiffTile.scala:503)
    at geotrellis.raster.io.geotiff.GeoTiffTile.toArrayTile(GeoTiffTile.scala:495)
    at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:123)
    at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:83)
    at geotrellis.raster.io.geotiff.SinglebandGeoTiff$.apply(SinglebandGeoTiff.scala:101)
...
```
which we can work around via streaming reads (implicitly used when `maxTileSize` is set in `input.json`):

```
[
    {
        "name": "HyoojBounds",
        "format": "geotiff",
        "backend": {
            "type": "hadoop",
            "path": "file:///home/colin/tiles/biggertiff.tiff"
        },
        "cache": "NONE",
        "maxTileSize": 256
    }
]
```
Running with these settings gives:
```
java.lang.RuntimeException: Cannot construct grid bounds of this size: 60000 x 60000
	at scala.sys.package$.error(package.scala:27)
	at geotrellis.raster.GridBounds.<init>(GridBounds.scala:78)
	at geotrellis.raster.GridBounds$.apply(GridBounds.scala:32)
	at geotrellis.raster.GridBounds.intersection(GridBounds.scala:181)
	at geotrellis.raster.crop.SinglebandTileCropMethods$class.crop(SinglebandTileCropMethods.scala:36)
	at geotrellis.raster.package$withTileMethods.crop(package.scala:53)
...
```
Now I can poke around with things and ponder a solution.

**Comment by fosskers** [comment]
This might be a nearly free fix. More news tomorrow.

**Comment by fosskers** [comment]
See #2292 .
