### ISSUE TITLE
Problem with Austria_Lambert CRS

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#2528]
The problem happens during this dataset processing.

```
scala> val path: String = "400390.tif"
path: String = 400390.tif

scala> val geoTiff: SinglebandGeoTiff = GeoTiffReader.readSingleband(path)
log4j:WARN No appenders could be found for logger (geotrellis.raster.io.geotiff.LazySegmentBytes).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
scala.MatchError: Some() (of class scala.Some)
  at geotrellis.raster.io.geotiff.reader.GeoTiffCSParser.getEllipsoidInfo(GeoTiffCSParser.scala:570)
  at geotrellis.raster.io.geotiff.reader.GeoTiffCSParser.createGeoTiffCSParameters(GeoTiffCSParser.scala:172)
  at geotrellis.raster.io.geotiff.reader.GeoTiffCSParser.geoTiffCSParameters$lzycompute(GeoTiffCSParser.scala:78)
  at geotrellis.raster.io.geotiff.reader.GeoTiffCSParser.geoTiffCSParameters(GeoTiffCSParser.scala:78)
  at geotrellis.raster.io.geotiff.reader.GeoTiffCSParser.model(GeoTiffCSParser.scala:80)
  at geotrellis.raster.io.geotiff.tags.TiffTags.crs$lzycompute(TiffTags.scala:236)
  at geotrellis.raster.io.geotiff.tags.TiffTags.crs(TiffTags.scala:234)
  at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readGeoTiffInfo(GeoTiffReader.scala:356)
  at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:98)
  at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:68)
  at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readSingleband(GeoTiffReader.scala:44)
  ... 42 elided
```

```
$ gdalinfo -proj4 400390.tif 
Driver: GTiff/GeoTIFF
Files: 400390.tif
Size is 10001, 10001
Coordinate System is:
PROJCS["MGI_Austria_Lambert",
    GEOGCS["GCS_MGI",
        DATUM["Militar_Geographische_Institute",
            SPHEROID["Bessel_1841",6377397.155,299.1528128,
                AUTHORITY["EPSG","7004"]],
            AUTHORITY["EPSG","6312"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["standard_parallel_1",49],
    PARAMETER["standard_parallel_2",46],
    PARAMETER["latitude_of_origin",47.5],
    PARAMETER["central_meridian",13.33333333333333],
    PARAMETER["false_easting",400000],
    PARAMETER["false_northing",400000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
PROJ.4 string is:
'+proj=lcc +lat_1=49 +lat_2=46 +lat_0=47.5 +lon_0=13.33333333333333 +x_0=400000 +y_0=400000 +datum=hermannskogel +units=m +no_defs '
Origin = (389999.956912119989283,390000.198657808825374)
Pixel Size = (1.000000000000000,-1.000000000000000)
Metadata:
  AREA_OR_POINT=Area
  DataType=Generic
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  389999.957,  390000.199) ( 13d12' 2.78"E, 47d24'35.78"N)
Lower Left  (  389999.957,  379999.199) ( 13d12' 3.59"E, 47d19'11.80"N)
Upper Right (  400000.957,  390000.199) ( 13d20' 0.05"E, 47d24'36.06"N)
Lower Right (  400000.957,  379999.199) ( 13d20' 0.05"E, 47d19'12.08"N)
Center      (  395000.457,  384999.699) ( 13d16' 1.62"E, 47d21'54.00"N)
Band 1 Block=128x128 Type=Float32, ColorInterp=Gray
  NoData Value=-3.4028234663852886e+38
```

The dataset: http://gis.ktn.gv.at/OGD/Geographie_Planung/ogd-10m-at.zip

**Comment by pomadchin** [comment]
Was fixed here: https://github.com/locationtech/geotrellis/pull/2403
