### ISSUE TITLE
stitch the croped TileLayerRDD crashed

### ISSUE THREAD

**Issue by Frophie** [locationtech/geotrellis#2549]
I'm trying to use the TileLayerRDD's crop method and stitch the crop result to write a single TIFF result.
This is the test code:
```
val tileRDD = sc.hadoopMultibandGeoTiffRDD(path)
val (_, metadata) = tileRDD.
      collectMetadata[SpatialKey](FloatingLayoutScheme(256))
val tiledRdd: RDD[(SpatialKey, MultibandTile)] = tileRDD.tileToLayout[SpatialKey](metadata)
val tileLayerRDD: MultibandTileLayerRDD[SpatialKey] = MultibandTileLayerRDD(tiledRdd, metadata)
val cropedRDD = tileLayerRDD.crop(Extent(531500.0, 7735000.0, 531600.0, 7735200.0))
val stitched = cropedRDD.stitch()
val geotiff = GeoTiff(stitched, cropedRDD.metadata.crs)
val pathHadoop = new Path(pathR)
geotiff.write(pathHadoop, sc.hadoopConfiguration)
```
and got crash like this:
```
20160
java.lang.ArrayIndexOutOfBoundsException: 20160
    at geotrellis.raster.UByteRawArrayTile.update(UByteArrayTile.scala:68)
    at geotrellis.raster.MutableArrayTile$class.set(MutableArrayTile.scala:56)
    at geotrellis.raster.UByteArrayTile.set(UByteArrayTile.scala:28)
    at geotrellis.raster.MutableArrayTile$class.update(MutableArrayTile.scala:89)
    at geotrellis.raster.UByteArrayTile.update(UByteArrayTile.scala:28)
    at geotrellis.raster.stitch.Stitcher$MultibandTileStitcher$$anonfun$stitch$4$$anonfun$apply$1.apply$mcVI$sp(Stitcher.scala:102)
    at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
    at geotrellis.raster.stitch.Stitcher$MultibandTileStitcher$$anonfun$stitch$4.apply(Stitcher.scala:101)
    at geotrellis.raster.stitch.Stitcher$MultibandTileStitcher$$anonfun$stitch$4.apply(Stitcher.scala:100)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
    at geotrellis.raster.stitch.Stitcher$MultibandTileStitcher$.stitch(Stitcher.scala:100)
    at geotrellis.raster.stitch.Stitcher$MultibandTileStitcher$.stitch(Stitcher.scala:80)
    at geotrellis.spark.stitch.TileLayoutStitcher$.stitch(StitchRDDMethods.scala:49)
    at geotrellis.spark.stitch.SpatialTileLayoutRDDStitchMethods.stitch(StitchRDDMethods.scala:58)
```
I fount note "Makes the assumption that all tiles are of equal size such that they can be placed in a grid layout." in StitchRDDMethods.scala, and i read the code found it uses the first tile's col/row count to calculate, but after crop the tile's size isn't same any more.

I hope the TileLayerRDD' stitch method can stitch tiles with different size, as long as they are in one layout.Then, my code above will work.

btw: 
as @pomadchin's advice, i tried "clamp = false" crop and stitch, and the result is quite wrong, a screenshot here ![alt](https://pasteboard.co/H315oTQ.png).

I also using @pomadchin's filter code tested "filter by extent intersection, stitch and crop the result stitch" , this works good.
but i still prefer to use TileLayerRDD's accurate crop and stitch if it's possible.
I suppose, maybe it's performance will be better than "filter by extent intersection, stitch and crop the result stitch" ?

**Comment by pomadchin** [comment]
Thanks for the issue! My bad, I forgot our API. 

Yes, we need a smarter crop function probably, but for now the workaround would be: 

```scala
layer
  .filter()
  .where(Intersects(poly))
  .result
  .stitch
  .crop(poly)
```

**Comment by Frophie** [comment]
@pomadchin Though this workaround can do the crop-writetoTIFF thing, but it can't help with my situation.
My fault not explained clear, I'm not the final user, and I provide a write operation for ```TileLayerRDD``` to the user, if they give a path which end with TIFF's extension, then I do stitch and write in one TIFF, if they give a dictionary, then i write the tiles with ```saveToHadoop(keyToUri: K => String)``` which is not stitched.
the write operation is separate with crop or read or slope, and in write, i don't know where the ```TileLayerRDD``` come from, maybe it's after crop, myabe it's after slope or aspect, maybe it's just read in. but if after crop it will crash. 
Their relationship is as same as other calculation between stitch, stitch don't know where the ```TileLayerRDD``` come from too. 
So,  I can't use your workaround in this situation, and can't avoid the crash. 
Just want to let you know.
I thought maybe you could slove the crash first.

**Comment by echeipesh** [comment]
I think the problem here is that `crop` is just ill defined for RDD case.
The two alternatives really are:

1. Crop each tile pixel to bounding box of intersection of polygon and tile extent (`clamp = true`).
- Ends up with tiles that break `TileLayerMetadata`, can't be stitched
2. Crop each tile pixels to bounding box of crop polygon (`clamp = false`)
- Ends up with tiles that have way to many buffered pixels, over stitched

What we actually want is:
Crop each tile to the pixels of polygon but use the same dimension of the tile. If polygon does not intersect tile, drop the tile. This is exactly what [`TileLayerRDD.mask`](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/mask/Mask.scala#L79-L88) will do. 
So I think using `tileLayerRDD.mask(Extent(531500.0, 7735000.0, 531600.0, 7735200.0)))` instead of `tileLayerRDD.crop(Extent(531500.0, 7735000.0, 531600.0, 7735200.0))` would solve the issue.

The API issue here is that [`tileLayerRDD.crop`](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/crop/LayerRDDCropMethods.scala#L34-L37) should be returning `RDD[(K, V)] with Metadata[M]` rather than `RDD[(K, V)]` or it should calling `Mask`, which is the intuitive implementation here. I would lean towards the latter.

**Comment by Frophie** [comment]
I think mask is as same as (clamp = false), but really different from (clamp = true), like this:
![image](https://user-images.githubusercontent.com/9249196/35021291-34c4e328-fb6b-11e7-87a4-c52e5690d3c8.png)
And I think, the desire for a crop(clamptrue) result isn't very excessive.

**Comment by Frophie** [comment]
Original TIFF:
https://www.dropbox.com/s/uncfja7pin6sddp/MBTest.tif?dl=0

**Comment by echeipesh** [comment]
Just to clarify in your use-case its important that the tiles from `tileLayerRDD` that partially intersect `Extent(531500.0, 7735000.0, 531600.0, 7735200.0)` should be cropped, losing some columns and/or rows. If so, its just the behavior of the `.stitch` method thats not acceptable?

**Comment by Frophie** [comment]
Yes,  just the behavior of the .stitch method that's not correct in this case of  non-uniform tile sizes .
