### ISSUE TITLE
`clipToGrid` fails with valid geometries

### ISSUE THREAD

**Issue by mojodna** [locationtech/geotrellis#2556]
Using a variant of VectorPipe (@lossyrob knows more about this), I'm assembling geometries from OSM. Before writing them out, I'm ensuring that they're valid with `isValid`.

However, when attempting to write them out to vector tiles, I clip them to a `WebMercator` grid @ zoom 15. Initially, I was getting `TopologyException`s:

```
com.vividsolutions.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( -3901750.606 -694727.58, -3901750.6574999997 -694727.58 ) and LINESTRING ( -3901750.606 -694727.58, -3901750.6575 -694727.58 ) [ (-3901750.606, -694727.58, NaN) ]
        at com.vividsolutions.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:145)
        at com.vividsolutions.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:94)
        at com.vividsolutions.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:59)
        at com.vividsolutions.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:237)
        at com.vividsolutions.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:189)
        at com.vividsolutions.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:92)
        at com.vividsolutions.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:96)
        at com.vividsolutions.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:58)
        at com.vividsolutions.jts.geom.Geometry.intersection(Geometry.java:1338)
        at geotrellis.vector.Geometry$class.intersection(Geometry.scala:79)
        at geotrellis.vector.Line.intersection(Line.scala:53)
        at geotrellis.spark.clip.ClipToGrid$.clipFeatureToExtent(ClipToGrid.scala:81)
        at geotrellis.spark.clip.ClipToGrid$$anonfun$apply$7.apply(ClipToGrid.scala:124)
        at geotrellis.spark.clip.ClipToGrid$$anonfun$apply$7.apply(ClipToGrid.scala:124)
        at geotrellis.spark.clip.ClipToGrid$.geotrellis$spark$clip$ClipToGrid$$clipToKey$1(ClipToGrid.scala:180)
        at geotrellis.spark.clip.ClipToGrid$$anonfun$3.apply(ClipToGrid.scala:188)
        at geotrellis.spark.clip.ClipToGrid$$anonfun$3.apply(ClipToGrid.scala:188)
        at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
        at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:438)
        at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:199)
        at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:338)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

After this patch to reduce precision (against the `1.2` branch), `clipToGrid` still fails, albeit less frequently:

```patch
diff --git i/spark/src/main/scala/geotrellis/spark/clip/ClipToGrid.scala w/spark/src/main/scala/geotrellis/spark/clip/ClipToGrid.scala
index 83a67a611..09d4422d7 100644
--- i/spark/src/main/scala/geotrellis/spark/clip/ClipToGrid.scala
+++ w/spark/src/main/scala/geotrellis/spark/clip/ClipToGrid.scala
@@ -78,7 +78,7 @@ object ClipToGrid {
     if(preds.covers(e)) { Some(Feature(e, feature.data)) }
     else if(preds.coveredBy(e)) { Some(feature) }
     else {
-      feature.geom.intersection(e).toGeometry.map { g =>
+      feature.geom.intersectionSafe(e).toGeometry.map { g =>
         Feature(g, feature.data)
       }
     }
```

After the above patch:

```
com.vividsolutions.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( -9734560.943790546 5102918.915938026, -9734810.243790178 5102925.764830882 ) and LINESTRING ( -9736026.821109207 5103584.427810077, -1216877.4903000072 637882.0769661946 ) [ (-9734768.091045868, 5102924.606789848, NaN) ]
```

To reproduce:

```scala
import geotrellis.proj4.{LatLng, WebMercator}
import geotrellis.spark._
import geotrellis.spark.tiling._
import geotrellis.vector.io._

// 11.5GB, sorry
val ways = spark.read.orc("s3://osm-pds-tmp/way-geoms-20180101/part-00000-3b0995db-715e-44b5-a539-8e7edb6c882a-c000.snappy.orc")
    .where('geom.isNotNull and size('tags) > 0)

val geometries = ways
    .rdd
    .map { row =>
        row.getAs[scala.Array[Byte]]("geom").readWKB.reproject(LatLng, WebMercator)
    }

val baseLayout = ZoomedLayoutScheme(WebMercator).levelForZoom(15).layout

val griddedPoints = geometries
    .clipToGrid(baseLayout)
    .count
```

Should `clipFeatureToExtent` `try` and drop failing geometries, or is there a better way to handle these geometries (set `geotrellis.jts.precision.type` or `geotrellis.jts.simplification.scale` since coordinates are already in "meters")?

(What's the best way to set these when using `spark-shell` or a Zeppelin notebook?)

Thanks!

**Comment by jpolchlo** [comment]
Hmm.  So, I think this might relate to a known problem in JTS (following quote taken from https://github.com/locationtech/jts/issues/120):

> Then, the reason that the difference method throws a TopologyException is due to a long-standing issue in the current JTS overlay algorithm. It is susceptible to robustness failures caused by vertices which lie very close, but not coincident with, other line segments. This is a classic situation for this to happen - two geometries which represent a similar area, but are derived from different sources. (And in this case it looks like the res2 geometry has been reprojected, which is also a classic way to introduce small variations in coordinate values.) As was pointed out on the NTS issue, the best way to avoid these kinds of robustness issues is to round off the coordinate values to some reasonable precision model (ideailly based on the accuracy of the source data).

As you can see, slight variations (as in the near-coincident geometry of the first exception you show), and very close vertices (as in the second exception, where one line is very small relative to the other line) cause problems.

We are grappling with the best way to address numerical problems in vector code throughout the library, but geometry simplification is a hard problem without a generally-accepted solution.  (And I believe OSM data is pathologically ill-conditioned in many cases, not to mention WebMercator is a horrible projection for numerical precision.)

I think the first thing to try is to set `geotrellis.jts.simplification.scale` to a smaller value.  Say `1e2`.  If you're not setting the value explicitly, it defaults to such a high value that you're basically getting no effect from calling the simplifier (which is called by `intersectionSafe`).  Though, I'm sorry to report that I've not been able to successfully set an `application.conf` through `spark-shell`; I've never tried to do it in Zeppelin.  Please report if you figure out how.  Maybe @echeipesh, @lossyrob, or @pomadchin have some suggestions?

We should be able to work this out, since I was able to compute the intersection of your geometries using the JTS test builder application, and the SBT console, for that matter:
```scala
 scala> val l1 = Line(-9734560.943790546 -> 5102918.915938026, -9734810.243790178 -> 5102925.764830882)
l1: geotrellis.vector.Line = LINESTRING (-9734560.943790546 5102918.915938026, -9734810.243790178 5102925.764830882)

scala> val l2 = Line(-9736026.821109207 -> 5103584.427810077, -1216877.4903000072 -> 637882.0769661946 )
l2: geotrellis.vector.Line = LINESTRING (-9736026.821109207 5103584.427810077, -1216877.4903000072 637882.0769661946)

scala> l1.intersection(l2)
res235: geotrellis.vector.OneDimensionAtLeastOneDimensionIntersectionResult = PointResult(POINT (-9734768.091045868 5102924.606789848))

scala> l1.intersectionSafe(l2)
res236: geotrellis.vector.TwoDimensionsTwoDimensionsIntersectionResult = PointResult(POINT (-9734768.091045868 5102924.606789848))
```
(In fact, I'm a bit puzzled how you arrived at this exception in light of this console transcript.)

**Comment by lossyrob** [comment]
One thing to check for data integrity's sake is to ensure all the incoming geometries are valid.

e.g.

What does

```scala
val ways = spark.read.orc("s3://osm-pds-tmp/way-geoms-20180101/part-00000-3b0995db-715e-44b5-a539-8e7edb6c882a-c000.snappy.orc")
    .where('geom.isNotNull and size('tags) > 0)

val geometries = ways
    .rdd
    .map { row =>
        row.getAs[scala.Array[Byte]]("geom").readWKB.reproject(LatLng, WebMercator)
    }

val (validCount, invalidCount) =
  geometries.
    map { g => if(g.isValid) (1, 0) else (0, 1) }.
    .reduce { case ((vc1, ivc1), (vc2, ivc2)) => (vc1 + vc2, ivc1 + ivc2) }
```

produce? You'd hope to have `(N, 0)`, which would mean no invalid geometries.

In JTS, when you try to operate on invalid geometries, things go badly. This is not to say that even probably this is the problem - Topo exceptions tend to happen even on valid geoms. It's one of the biggest pain points when working with JTS.

A hacky workaround that is the go-to for Topo exceptions is to `.buffer(0)` everything. Why? I don't know. But it tends to work a lot.

```scala
val geometries = ways
    .rdd
    .map { row =>
        val geom =
	      row.getAs[scala.Array[Byte]]("geom").readWKB.reproject(LatLng, WebMercator)
	   Geometry(geom.jtsGeom.buffer(0))
    }
```

**Comment by mojodna** [comment]
For `spark-shell`, adding `--conf spark.driver.extraJavaOptions="-Dconfig.file=/home/hadoop/application.conf"` to the list of args combined with an `application.conf` that looks like the following worked (to set `geotrellis.jts.simplification.scale` anyway):

```
geotrellis {
  jts {
    simplification {
      scale = 1e2
    }
  }
}
```

I think it'd either need to be included in supplemental JARs or as an option when starting Zeppelin.

@lossyrob good call. The WGS84 geometries were valid, but 46 of the reprojected geometries were not.

Draft UDFs for `Dataset`-land that I used instead (the `reduce` was complaining):

```scala
val isValid = udf((geom: Array[Byte]) => {
    geom match {
        case null => true
        case _ => geom.readWKB.isValid
    }
})

val reproject = udf((geom: Array[Byte]) => {
    geom match {
        case null => null
        case _ => geom.readWKB.reproject(LatLng, WebMercator).toWKB(3857)
    }
})
```

Re-running now, filtered to valid Web Mercator geoms.

**Comment by mojodna** [comment]
That looks like it was the problem (invalid Web Mercator geometries from valid WGS 84 ones).

Thanks, all!
