### ISSUE TITLE
readMultiband Exception thrown when reading single band tif with extra alpha band

### ISSUE THREAD

**Issue by genevieve-sarm** [locationtech/geotrellis#2577]
Hi,

The readMultiband function is not able to handle the case when tif file band structure looks has alpha band separated from the single band:
Band 1 Block=1625x1947 Type=Byte, ColorInterp=Palette
  Mask Flags: PER_DATASET ALPHA 
  Color Table (RGB with 256 entries)
    0: 0,0,0,255
    1: 0,75,40,255
    2: 0,75,40,255
    3: 0,75,40,255
    4: 0,75,40,255
    5: 0,75,40,255
    6: 0,75,40,255
    7: 0,75,40,255
    8: 0,75,40,255
    9: 0,75,40,255
   10: 0,75,40,255
   //<... up to 255 info>
Band 2 Block=1625x1947 Type=Byte, ColorInterp=Alpha
(Sample gdalinfo on tif is attached)

Exception looks like:
scala> val geotiff = GeoTiffReader.readMultiband(reader)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.ArrayIndexOutOfBoundsException: 1
  at geotrellis.raster.io.geotiff.ArraySegmentBytes$$anonfun$getSegments$1.apply(ArraySegmentBytes.scala:49)
  at geotrellis.raster.io.geotiff.ArraySegmentBytes$$anonfun$getSegments$1.apply(ArraySegmentBytes.scala:49)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
  at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:463)
  at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
  at scala.collection.Iterator$$anon$12.next(Iterator.scala:445)
  at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
  at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:333)
  at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.toArrayTile(GeoTiffMultibandTile.scala:325)
  at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readMultiband(GeoTiffReader.scala:177)
  at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readMultiband(GeoTiffReader.scala:153)
  ... 42 elided

Tried the following (which causes to lose the data from alpha band):
 - reading with readSingleband is not causing exception 
 - removing the extra alpha band from the image (Band 2 Block=1625x1947 Type=Byte, ColorInterp=Alpha) by using `gdal_translate -b 1 -a_nodata 0 extra_alpha_band.tif band_2_remove.tif` 

See attached files for more info. 

Thanks for your help.
[sbt_console.log](https://github.com/locationtech/geotrellis/files/1760424/sbt_console.log)
[gdalinfo_extra_alpha_band.txt](https://github.com/locationtech/geotrellis/files/1760425/gdalinfo_extra_alpha_band.txt)

I was going to attach the tif file, but I am not able to attach it here (not supported file type for attachment).

**Comment by marcuswr** [comment]
Test image resulting in the stack trace documented above.
[test.zip](https://github.com/locationtech/geotrellis/files/1760489/test.zip)

**Comment by pomadchin** [comment]
Hey @genevieve-sarm and @marcuswr this is the only tiff you experience problem with? or all the tiffs generated the same way have this problem.

**Comment by pomadchin** [comment]
The problem of this tiff that it consists of a single strip. The workaround would be to persist it in somehow better way. As a workaround i can suggest you to use:

```
gdal_translate in.tif out.tif -co TILED=YES -co COPY_SRC_OVERVIEWS=YES -co COMPRESS=DEFLATE
```

But this is still a bug (impossibility to handle striped multibands) and we'll fix it.

**Comment by marcuswr** [comment]
This is the only image we currently have which exhibits this issue. We did not generate it ourselves, and unfortunately we don't know what software was used to generate the image.

**Comment by pomadchin** [comment]
hey @genevieve-sarm it's already in `2.0-RC2`
