### ISSUE TITLE
FileCOGLayerReader can't read on Windows operating system

### ISSUE THREAD

**Issue by Frophie** [locationtech/geotrellis#2608]
Tried the [COG example](https://github.com/locationtech/geotrellis/blob/master/doc-examples/src/main/scala/geotrellis/doc/examples/spark/COGSparkExamples.scala) on Windows 10 locally, seems FileCOGLayerReader can't read on Windows.
```
java.net.URISyntaxException: Illegal character in authority at index 7: file://E:\Work\GeoTiff\COG\catalog\zoom_cog_layer\0_0\0.tiff
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseAuthority(URI.java:3186)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at geotrellis.spark.io.file.cog.FileCOGLayerReader$$anonfun$read$3.apply(FileCOGLayerReader.scala:70)
	at geotrellis.spark.io.file.cog.FileCOGLayerReader$$anonfun$read$3.apply(FileCOGLayerReader.scala:70)
	at geotrellis.spark.io.cog.COGLayerReader$$anonfun$7$$anonfun$apply$3$$anonfun$apply$4.apply(COGLayerReader.scala:265)
	at geotrellis.spark.io.cog.COGLayerReader$$anonfun$7$$anonfun$apply$3$$anonfun$apply$4.apply(COGLayerReader.scala:262)
```

**Comment by jbouffard** [comment]
@Frophie I think the issue is with how the file path is formatted rather than with the `FileCOGLayerReader`. As the path you're trying to read can't be turned into a `URI`

```
scala> new URI("file://E:\Work\GeoTiff\COG\catalog\zoom_cog_layer\0_0\0.tiff")
<console>:1: error: invalid escape character
new URI("file://E:\Work\GeoTiff\COG\catalog\zoom_cog_layer\0_0\0.tiff")
                   ^
<console>:1: error: invalid escape character
new URI("file://E:\Work\GeoTiff\COG\catalog\zoom_cog_layer\0_0\0.tiff")
                        ^
<console>:1: error: invalid escape character
new URI("file://E:\Work\GeoTiff\COG\catalog\zoom_cog_layer\0_0\0.tiff")
                                ^
<console>:1: error: invalid escape character
new URI("file://E:\Work\GeoTiff\COG\catalog\zoom_cog_layer\0_0\0.tiff")
                                    ^
<console>:1: error: invalid escape character
new URI("file://E:\Work\GeoTiff\COG\catalog\zoom_cog_layer\0_0\0.tiff")
                                            ^
```

From [this StackOverflow issue](https://stackoverflow.com/questions/8323760/java-get-uri-from-filepath), it looks like you can replace the `\`s in your file path with `/`s, and it should still work.

Could you try doing that and seeing if it works?

**Comment by Frophie** [comment]
Actually my input is `/`, "file://E:\Work\GeoTiff\COG\catalog\zoom_cog_layer\0_0\0.tiff" is a path after some inner transform.
Here is my code:
```
    val reader = FileCOGLayerReader("E:/Work/GeoTiff/COG/catalog")(sc)

    val layer = reader.read[SpatialKey, MultibandTile](LayerId("cog_layer", 13))
    println(layer.count())
```

**Comment by Frophie** [comment]
And `FileLayerReader("E:/Work/GeoTiff/COG/fileCatalog")(sc)` works well with avro catalog, so I think we need to check why `FileCOGLayerReader` is different.

**Comment by jbouffard** [comment]
@Frophie Ah, I see. I'm looking into the issue now. Would you be okay with testing out possible solutions? I don't have a Windows machine or virtual environment to test on.

**Comment by Frophie** [comment]
@jbouffard Yes, of course, just tell me what to do, and I will try.

**Comment by jbouffard** [comment]
Thanks, @Frophie. I'll probably contact on Gitter later today to go over some possible solutions.

**Comment by Frophie** [comment]
@lossyrob  You are right about the "\" to "/" suggestion. The path turns into "\" after [`File.getAbsolutePath`](https://github.com/locationtech/geotrellis/blob/86e0f854f7b7597ebb6f0eb3c636155918ec6176/spark/src/main/scala/geotrellis/spark/io/file/KeyPathGenerator.scala#L31), so I do a replace after it:
```
(index: BigInt) => new File(f, Index.encode(index, maxWidth)).getAbsolutePath
      .replaceAll("\\\\", "/")
```
Then, the reading process succeed.
