### ISSUE TITLE
Some tif files can't read by sc.hadoopMultibandGeoTiffRDD(path) any more in 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by Frophie** [locationtech/geotrellis#2627]
Some tif files can't read by `sc.hadoopMultibandGeoTiffRDD(path)` any more in 2.0.0-SNAPSHOT.
They can be read with 1.2.1.
[test.zip](https://github.com/locationtech/geotrellis/files/1919739/test.zip)

```
scala.MatchError: 0 (of class java.lang.Integer)
    at geotrellis.raster.io.geotiff.NewSubfileType$.fromCode(NewSubfileType.scala:34)
    at geotrellis.raster.io.geotiff.NewSubfileType$.fromCode(NewSubfileType.scala:33)
    at geotrellis.raster.io.geotiff.reader.GeoTiffReader$$anonfun$1.apply(GeoTiffReader.scala:440)
    at geotrellis.raster.io.geotiff.reader.GeoTiffReader$$anonfun$1.apply(GeoTiffReader.scala:440)
    at scala.Option.map(Option.scala:146)
    at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.geotrellis$raster$io$geotiff$reader$GeoTiffReader$$getGeoTiffInfo$1(GeoTiffReader.scala:440)
    at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readGeoTiffInfo(GeoTiffReader.scala:487)
    at geotrellis.spark.io.hadoop.HadoopGeoTiffInfoReader.getGeoTiffInfo(HadoopGeoTiffInfoReader.scala:54)
    at geotrellis.spark.io.GeoTiffInfoReader$$anonfun$1.apply(GeoTiffInfoReader.scala:81)
    at geotrellis.spark.io.GeoTiffInfoReader$$anonfun$1.apply(GeoTiffInfoReader.scala:79)
```

**Comment by pomadchin** [comment]
Thanks for your report!
