### ISSUE TITLE
Initialization of Tiles w/ more cells than IntMax throws

### ISSUE THREAD

**Issue by fosskers** [locationtech/geotrellis#2646]
```
scala> UByteArrayTile.empty(46500, 46500)
                         ^
java.lang.NegativeArraySizeException
  at scala.reflect.ManifestFactory$$anon$6.newArray(Manifest.scala:93)
  at scala.reflect.ManifestFactory$$anon$6.newArray(Manifest.scala:91)
  at scala.Array$.ofDim(Array.scala:218)
  at geotrellis.raster.UByteArrayTile$.fill(UByteArrayTile.scala:300)
  at geotrellis.raster.UByteArrayTile$.empty(UByteArrayTile.scala:269)
  at geotrellis.raster.UByteArrayTile$.empty(UByteArrayTile.scala:254)
  ... 40 elided
```
If `.empty` is just multiplying its arguments before calling `.ofDim`, then it makes sense than we'd hit an overflow. Can this error case be modelled in the types somehow? If not, can a more descriptive exception be thrown?

**Comment by fosskers** [comment]
Is this still an issue?

**Comment by pomadchin** [comment]
@fosskers sadly, yes ):

**Comment by fosskers** [comment]
Kk I'll leave it open.
