### ISSUE TITLE
OutOfMemoryError Encountered When Trying to Ingest a COGLayer But Not When Ingesting an AvroLayer

### ISSUE THREAD

**Issue by jbouffard** [locationtech/geotrellis#2759]
I'm currently trying to ingest a layer in GeoTrellis to S3 as both an `AvroLayer` and as a `COGLayer`. I was able to ingest the layer as an `AvroLayer`, but got an `OutOfMemoryError` when trying to ingest it as a `COGLayer`. Both of these ingests occurred in the same environment, so I'd assume that if one failed the other should as well.

This is the logic I used to create the layer:

```scala
      val inputRdd: RDD[(ProjectedExtent, MultibandTile)] =
        HadoopGeoTiffRDD.spatialMultiband("/tmp/landsat-multiband-band-cropped.tif")

      val (_, rasterMetaData) = TileLayerMetadata.fromRdd(inputRdd, FloatingLayoutScheme(256))

      val tiled: RDD[(SpatialKey, MultibandTile)] =
        inputRdd
          .tileToLayout(rasterMetaData.cellType, rasterMetaData.layout)

      val layoutScheme = ZoomedLayoutScheme(WebMercator, tileSize = 256)

      val (zoom, reprojected): (Int, RDD[(SpatialKey, MultibandTile)] with Metadata[TileLayerMetadata[SpatialKey]]) =
MultibandTileLayerRDD(tiled, rasterMetaData).reproject(WebMercator, layoutScheme)
```

And this is how I saved the `AvroLayer`:

```scala
val avroWriter = S3LayerWriter("geotrellis-test", "daunnc/cog-benchmakr/avro-3")

Pyramid.upLevels(reprojected, layoutScheme, zoom) { (rdd, z) =>
  val layerId = LayerId("avro-multiband-band-layer", z)
  avroWriter.write(layerId, rdd, ZCurveKeyIndexMethod)
}
```

And this is how I wrote the `COGLayer`:

```scala
val cogWriter = COGLayerWriter("geotrellis-test/daunnc/cog-benchmakr/cog-3")
cogWriter.write("cog-multiband-band-layer", reprojected, zoom, ZCurveKeyIndexMethod)
```

The file I used can be found in: `s3://geotrellis-test`

**Comment by jbouffard** [comment]
This is the full stacktrace:

```
[error] (pool-23-thread-21) java.lang.OutOfMemoryError: Java heap space
[error] (pool-24-thread-22) java.lang.OutOfMemoryError: Java heap space
[error] java.lang.OutOfMemoryError: Java heap space
[error] 	at scala.reflect.ManifestFactory$$anon$7.newArray(Manifest.scala:101)
[error] 	at scala.reflect.ManifestFactory$$anon$7.newArray(Manifest.scala:99)
[error] 	at scala.Array$.ofDim(Array.scala:218)
[error] 	at geotrellis.raster.UShortArrayTile$.ofDim(UShortArrayTile.scala:266)
[error] 	at geotrellis.raster.UShortArrayTile$.empty(UShortArrayTile.scala:295)
[error] 	at geotrellis.raster.ArrayTile$.empty(ArrayTile.scala:433)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$crop$1$$anonfun$7.apply(GeoTiffMultibandTile.scala:576)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$crop$1$$anonfun$7.apply(GeoTiffMultibandTile.scala:576)
[error] 	at scala.Array$.fill(Array.scala:267)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$crop$1.apply(GeoTiffMultibandTile.scala:576)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$crop$1.apply(GeoTiffMultibandTile.scala:569)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:569)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:546)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:535)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.toArrayTile(GeoTiffMultibandTile.scala:527)
[error] 	at geotrellis.raster.io.geotiff.MultibandGeoTiff.withOverviews(MultibandGeoTiff.scala:144)
[error] 	at geotrellis.raster.io.geotiff.MultibandGeoTiff.withOverviews(MultibandGeoTiff.scala:27)
[error] 	at geotrellis.spark.io.cog.COGLayer$$anonfun$5$$anonfun$apply$2.apply(COGLayer.scala:206)
[error] 	at geotrellis.spark.io.cog.COGLayer$$anonfun$5$$anonfun$apply$2.apply(COGLayer.scala:176)
[error] 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
[error] 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
[error] 	at fs2.Stream$$anonfun$fs2$Stream$$getNext$1$2$$anonfun$apply$12.apply(Stream.scala:1393)
[error] 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85)
[error] 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:310)
[error] 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:292)
[error] 	at cats.effect.internals.Callback$AsyncIdempotentCallback$$anon$3.run(Callback.scala:142)
[error] 	at cats.effect.internals.TrampolineEC.cats$effect$internals$TrampolineEC$$localRunLoop(TrampolineEC.scala:62)
[error] 	at cats.effect.internals.TrampolineEC$$anonfun$execute$1.apply$mcV$sp(TrampolineEC.scala:54)
[error] 	at cats.effect.internals.TrampolineEC$$anonfun$execute$1.apply(TrampolineEC.scala:54)
[error] 	at cats.effect.internals.TrampolineEC$$anonfun$execute$1.apply(TrampolineEC.scala:54)
[error] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
[error] java.lang.OutOfMemoryError: Java heap space
[error] 	at scala.reflect.ManifestFactory$$anon$7.newArray(Manifest.scala:101)
[error] 	at scala.reflect.ManifestFactory$$anon$7.newArray(Manifest.scala:99)
[error] 	at scala.Array$.ofDim(Array.scala:218)
[error] 	at geotrellis.raster.UShortArrayTile$.ofDim(UShortArrayTile.scala:266)
[error] 	at geotrellis.raster.UShortArrayTile$.empty(UShortArrayTile.scala:295)
[error] 	at geotrellis.raster.ArrayTile$.empty(ArrayTile.scala:433)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$crop$1$$anonfun$7.apply(GeoTiffMultibandTile.scala:576)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$crop$1$$anonfun$7.apply(GeoTiffMultibandTile.scala:576)
[error] 	at scala.Array$.fill(Array.scala:267)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$crop$1.apply(GeoTiffMultibandTile.scala:576)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile$$anonfun$crop$1.apply(GeoTiffMultibandTile.scala:569)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:569)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:546)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.crop(GeoTiffMultibandTile.scala:535)
[error] 	at geotrellis.raster.io.geotiff.GeoTiffMultibandTile.toArrayTile(GeoTiffMultibandTile.scala:527)
[error] 	at geotrellis.raster.io.geotiff.MultibandGeoTiff.withOverviews(MultibandGeoTiff.scala:144)
[error] 	at geotrellis.raster.io.geotiff.MultibandGeoTiff.withOverviews(MultibandGeoTiff.scala:27)
[error] 	at geotrellis.spark.io.cog.COGLayer$$anonfun$5$$anonfun$apply$2.apply(COGLayer.scala:206)
[error] 	at geotrellis.spark.io.cog.COGLayer$$anonfun$5$$anonfun$apply$2.apply(COGLayer.scala:176)
[error] 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
[error] 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
[error] 	at fs2.Stream$$anonfun$fs2$Stream$$getNext$1$2$$anonfun$apply$12.apply(Stream.scala:1393)
[error] 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85)
[error] 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:310)
[error] 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:292)
[error] 	at cats.effect.internals.Callback$AsyncIdempotentCallback$$anon$3.run(Callback.scala:142)
[error] 	at cats.effect.internals.TrampolineEC.cats$effect$internals$TrampolineEC$$localRunLoop(TrampolineEC.scala:62)
[error] 	at cats.effect.internals.TrampolineEC$$anonfun$execute$1.apply$mcV$sp(TrampolineEC.scala:54)
[error] 	at cats.effect.internals.TrampolineEC$$anonfun$execute$1.apply(TrampolineEC.scala:54)
[error] 	at cats.effect.internals.TrampolineEC$$anonfun$execute$1.apply(TrampolineEC.scala:54)
[error] 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
[error] (pool-22-thread-17) java.lang.OutOfMemoryError: Java heap space
[error] java.lang.OutOfMemoryError: Java heap space
[error] 	at java.util.Arrays.copyOf(Arrays.java:3236)
[error] 	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
[error] 	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
[error] 	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
[error] 	at java.io.DataOutputStream.write(DataOutputStream.java:107)
[error] 	at geotrellis.raster.io.geotiff.writer.GeoTiffWriter.writeBytes(GeoTiffWriter.scala:76)
[error] 	at geotrellis.raster.io.geotiff.writer.GeoTiffWriter$$anonfun$appendCloudOptimized$2$$anonfun$apply$1.apply(GeoTiffWriter.scala:320)
[error] 	at geotrellis.raster.io.geotiff.writer.GeoTiffWriter$$anonfun$appendCloudOptimized$2$$anonfun$apply$1.apply(GeoTiffWriter.scala:319)
[error] 	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[error] 	at geotrellis.raster.io.geotiff.writer.GeoTiffWriter$$anonfun$appendCloudOptimized$2.apply(GeoTiffWriter.scala:319)
[error] 	at geotrellis.raster.io.geotiff.writer.GeoTiffWriter$$anonfun$appendCloudOptimized$2.apply(GeoTiffWriter.scala:318)
[error] 	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error] 	at geotrellis.raster.io.geotiff.writer.GeoTiffWriter.appendCloudOptimized(GeoTiffWriter.scala:318)
[error] 	at geotrellis.raster.io.geotiff.writer.GeoTiffWriter.write(GeoTiffWriter.scala:344)
[error] 	at geotrellis.raster.io.geotiff.writer.GeoTiffWriter$.write(GeoTiffWriter.scala:52)
[error] 	at geotrellis.spark.io.s3.cog.S3COGAsyncWriter.encodeRecord(S3COGLayerWriter.scala:147)
[error] 	at geotrellis.spark.io.s3.cog.S3COGAsyncWriter.encodeRecord(S3COGLayerWriter.scala:131)
[error] 	at geotrellis.spark.io.AsyncWriter$$anonfun$2.apply(AsyncWriter.scala:66)
[error] 	at geotrellis.spark.io.AsyncWriter$$anonfun$2.apply(AsyncWriter.scala:66)
[error] 	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85)
[error] 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:310)
[error] 	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:292)
[error] 	at cats.effect.IO$$anonfun$shift$1$$anon$8.run(IO.scala:817)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by CosmosEcho** [comment]
i had a same error for a 2G tiff.

**Comment by pomadchin** [comment]
Hey @CosmosEcho what exactly did you have? Are you writing a `COGLayer`? It's an experimental API so the bugs are pretty much expected there.

**Comment by CosmosEcho** [comment]
Hi @pomadchin , I am a new to the API. I had use Ingest, my code:
![image](https://user-images.githubusercontent.com/13760084/49412725-6a03cb00-f7a8-11e8-9da5-e89cd9780076.png)
my data is a 1.91G tif from UAV.
[
  {
    "name": "dataUav",
    "format": "multiband-geotiff",
    "backend": {
      "type": "hadoop",
      "path": "data/qac.tif"
    },
    "cache": "NONE"
  }
]

**Comment by pomadchin** [comment]
@CosmosEcho than it’s definitely not the same issue, if you’ll read topic more carefull - _not in Avro layers_; and you’re investing a default Avro layer. Tell me a little bit more: geotrellis version, gdalinfo of a tiff and your spark job parameters. Also cluster parameters: hon many nodes / memory / cpu it has.

**Comment by pomadchin** [comment]
P.S. you can insert the code here using github markdown to highlight instead of posting pictures.

**Comment by CosmosEcho** [comment]
@CosmosEcho Sorry！I need study more about geotrellis. I just want to build a simple server for my raster created by UAV, and see them in the browse. My build.sbt is that:
`scalaVersion := "2.11.8"

organization := "xxxx.xxxx.xxxx"

scalacOptions ++= Seq(
  "-deprecation",
  "-unchecked",
  "-Yinline-warnings",
  "-language:implicitConversions",
  "-language:reflectiveCalls",
  "-language:higherKinds",
  "-language:postfixOps",
  "-language:existentials",
  "-feature")
publishMavenStyle := true
publishArtifact in Test := false
pomIncludeRepository := { _ => false }

shellPrompt := { s => Project.extract(s).currentProject.id + " > " }

javaOptions += "-Xmx4G"

val gtVersion = "2.1.0"

dependencyOverrides ++= {
  val deps = Seq(
    "com.fasterxml.jackson.core" % "jackson-core" % "2.6.5",
    "com.fasterxml.jackson.core" % "jackson-databind" % "2.6.5",
    "com.fasterxml.jackson.core" % "jackson-annotations" % "2.6.5"
  )
  CrossVersion.partialVersion(scalaVersion.value) match {
    // if Scala 2.12+ is used
    case Some((2, scalaMajor)) if scalaMajor >= 12 => deps
    case _ => deps :+ "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.6.5"
  }
}

libraryDependencies ++= Seq(
  "org.locationtech.geotrellis" %% "geotrellis-spark" % gtVersion,
  "org.locationtech.geotrellis" %% "geotrellis-spark-etl" % gtVersion,
  "org.apache.spark" %% "spark-core" % "2.2.0",
  "com.typesafe.akka" %% "akka-actor"  % "2.4.17",
  "com.typesafe.akka" %% "akka-http" % "10.0.3",
  "org.scalatest" %% "scalatest" % "2.2.0" % "test"
)

assemblyShadeRules in assembly := {
  val shadePackage = "com.azavea.shaded.demo"
  Seq(
    ShadeRule.rename("com.google.common.**" -> s"$shadePackage.google.common.@1")
      .inLibrary(
        "com.azavea.geotrellis" %% "geotrellis-cassandra" % gtVersion,
        "com.github.fge" % "json-schema-validator" % "2.2.6"
      ).inAll
  )
}

Revolver.settings

assemblyMergeStrategy in assembly := {
  case "reference.conf" => MergeStrategy.concat
  case "application.conf" => MergeStrategy.concat
  case "META-INF/MANIFEST.MF" => MergeStrategy.discard
  case "META-INF\\MANIFEST.MF" => MergeStrategy.discard
  case "META-INF/ECLIPSEF.RSA" => MergeStrategy.discard
  case "META-INF/ECLIPSEF.SF" => MergeStrategy.discard
  case _ => MergeStrategy.first
}`
memory:16G
cpu:3.6G Hz
I get the info of tiff in arcmap:
`<TreeList><Raster_Information><Columns_and_Rows>29324, 23653</Columns_and_Rows><Number_of_Bands>4</Number_of_Bands><Cell_Size__X._Y_>2.56472e-007, 2.18196e-007</Cell_Size__X._Y_><Uncompressed_Size>2.58 GB</Uncompressed_Size><Format>TIFF</Format><Source_Type>Generic</Source_Type><Pixel_Type>unsigned integer</Pixel_Type><Pixel_Depth>8 Bit</Pixel_Depth><NoData_Value></NoData_Value><Colormap>absent</Colormap><Pyramids>level: 7, resampling: Nearest Neighbor</Pyramids><Compression>LZW</Compression><Mensuration_Capabilities>Basic</Mensuration_Capabilities><Status>Permanent</Status></Raster_Information><Extent><Top>32.1511889673</Top><Left>120.138729119</Left><Right>120.146249904</Right><Bottom>32.1460279773</Bottom></Extent><Spatial_Reference>GCS_WGS_1984<Linear_Unit></Linear_Unit><Angular_Unit>Degree (0.0174532925199433)</Angular_Unit><Datum>D_WGS_1984</Datum></Spatial_Reference><Statistics><Band_1>Statistics have not been calculated.<Build_Parameters></Build_Parameters><Min></Min><Max></Max><Mean></Mean><Std_dev.></Std_dev.><Classes></Classes></Band_1><Band_2>Statistics have not been calculated.<Build_Parameters></Build_Parameters><Min></Min><Max></Max><Mean></Mean><Std_dev.></Std_dev.><Classes></Classes></Band_2><Band_3>Statistics have not been calculated.<Build_Parameters></Build_Parameters><Min></Min><Max></Max><Mean></Mean><Std_dev.></Std_dev.><Classes></Classes></Band_3><Band_4>Statistics have not been calculated.<Build_Parameters></Build_Parameters><Min></Min><Max></Max><Mean></Mean><Std_dev.></Std_dev.><Classes></Classes></Band_4></Statistics></TreeList>
`

**Comment by pomadchin** [comment]
Ok, I still need `gdalinfo` to see at the tiff segments information.
Also can you provide your `spark-submit` command?

**Comment by CosmosEcho** [comment]
@pomadchin I got the info of tiff in gdalinfo:
`Driver: GTiff/GeoTIFF
Files: D:\IDEAProjects\Deotrellis-210-Demo\data\data-uav.tif
Size is 29324, 23653
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (120.138729119219920,32.151188967299596)
Pixel Size = (0.000000256472000,-0.000000218196000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  ( 120.1387291,  32.1511890) (120d 8'19.42"E, 32d 9' 4.28"N)
Lower Left  ( 120.1387291,  32.1460280) (120d 8'19.42"E, 32d 8'45.70"N)
Upper Right ( 120.1462499,  32.1511890) (120d 8'46.50"E, 32d 9' 4.28"N)
Lower Right ( 120.1462499,  32.1460280) (120d 8'46.50"E, 32d 8'45.70"N)
Center      ( 120.1424895,  32.1486085) (120d 8'32.96"E, 32d 8'54.99"N)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  Overviews: 14662x11827, 7331x5914, 3666x2957, 1833x1479, 917x740, 459x370, 230x185
  Mask Flags: PER_DATASET ALPHA
  Overviews of mask band: 14662x11827, 7331x5914, 3666x2957, 1833x1479, 917x740, 459x370, 230x185
  Unit Type: metre
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
  Overviews: 14662x11827, 7331x5914, 3666x2957, 1833x1479, 917x740, 459x370, 230x185
  Mask Flags: PER_DATASET ALPHA
  Overviews of mask band: 14662x11827, 7331x5914, 3666x2957, 1833x1479, 917x740, 459x370, 230x185
  Unit Type: metre
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
  Overviews: 14662x11827, 7331x5914, 3666x2957, 1833x1479, 917x740, 459x370, 230x185
  Mask Flags: PER_DATASET ALPHA
  Overviews of mask band: 14662x11827, 7331x5914, 3666x2957, 1833x1479, 917x740, 459x370, 230x185
  Unit Type: metre
Band 4 Block=256x256 Type=Byte, ColorInterp=Alpha
  Overviews: 14662x11827, 7331x5914, 3666x2957, 1833x1479, 917x740, 459x370, 230x185
  Unit Type: metre`

**Comment by pomadchin** [comment]
Should be good. It's LZW compressed and requires lots of memory to process. How much memory do you allocate during spark-submit?

**Comment by pomadchin** [comment]
P.S. [This is how to deal with markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by pomadchin** [comment]
I'm wondering what's your pipeline to run the ingestion?  I'm afraid that even 4GBs can be not enough; it looks like this tiff size would be only around 4gigs in uncompressed form, and you in addition need to run some operations on it.

@CosmosEcho lets move this discussion into our [gitter channel](https://gitter.im/geotrellis/geotrellis) as this issue is not about avro layers / basic questions but about COGs problems / features.

**Comment by CosmosEcho** [comment]
@pomadchin ok,thinks.
