### ISSUE TITLE
Some decompression fails mysteriously

### ISSUE THREAD

**Issue by jisantuc** [locationtech/geotrellis#2796]
I have a tif that's been turned into a COG. After turning it into a COG, for some zoom levels (all above a certain threshold, that I don't remember, but will edit to add shortly), the
when trying to get tiles from the overview chosen by `getClosestOverview`, I encounter an error
inflating the data:

```
java.util.zip.DataFormatException: incorrect header check
      at java.util.zip.Inflater.inflateBytes(Native Method)
      at java.util.zip.Inflater.inflate(Inflater.java:259)
      at java.util.zip.Inflater.inflate(Inflater.java:280)
      at geotrellis.raster.io.geotiff.compression.DeflateDecompressor.decompress(DeflateCompression.scala:70)
      at geotrellis.raster.io.geotiff.compression.Decompressor$$anon$1.decompress(Decompressor.scala:44)
      at geotrellis.raster.io.geotiff.compression.Decompressor$$anon$2.decompress(Decompressor.scala:72)
      at geotrellis.raster.io.geotiff.UInt16GeoTiffSegmentCollection$$anonfun$decompressGeoTiffSegment$2.apply(UInt16GeoTiffSegmentCollection.scala:29)
      at geotrellis.raster.io.geotiff.UInt16GeoTiffSegmentCollection$$anonfun$decompressGeoTiffSegment$2.apply(UInt16GeoTiffSegmentCollection.scala:29)
      at geotrellis.raster.io.geotiff.GeoTiffSegmentCollection$$anonfun$getSegments$2.apply(GeoTiffSegmentCollection.scala:46)
      at geotrellis.raster.io.geotiff.GeoTiffSegmentCollection$$anonfun$getSegments$2.apply(GeoTiffSegmentCollection.scala:45)
      at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
      at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
      at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
      at scala.collection.Iterator$$anon$12.next(Iterator.scala:445)
      at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
      at com.azavea.rf.common.utils.CogUtils$.cropGeoTiff(CogUtils.scala:227)
      at com.azavea.rf.common.utils.CogUtils$$anonfun$cropForZoomExtent$1.apply(CogUtils.scala:201)
      at com.azavea.rf.common.utils.CogUtils$$anonfun$cropForZoomExtent$1.apply(CogUtils.scala:201)
      at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
      at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
      at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      at java.lang.Thread.run(Thread.java:748)
```

The tif can be found at `s3://test.objects/example-incorrect-header.tif`

**Comment by lossyrob** [comment]
What were the commands used to turn the original file into the COG?

**Comment by jisantuc** [comment]
I thought this was better behaved before, but I just looked at gdalinfo on it and saw

```
Coordinate System is `'
```

which can't be good.

I set a slackbot reminder to revisit this Monday morning.

**Comment by jisantuc** [comment]
Seems like there are some other problems in the COG pipeline that was producing this issue -- https://github.com/raster-foundry/raster-foundry/issues/4043 -- so I'm closing for now
