### ISSUE TITLE
Can't write RasterRDD which extent across longitude 180 with ZCurveKeyIndexMethod

### ISSUE THREAD

**Issue by Frophie** [locationtech/geotrellis#2815]
Trying to ingest a set of global DEM tiffs, but found writing tiff with Extent(-180.0001388888889, 64.9998611111111, -178.99986111111113, 66.00013888888888) and with `ZCurveKeyIndexMethod` failed. Note that with `HilbertKeyIndexMethod` this process works.
 Here is the code:
```
    val tileRDD: RDD[(ProjectedExtent, MultibandTile)] = sc.hadoopMultibandGeoTiffRDD(path)

    val crs = CRS.fromEpsgCode(4326)
    val zoom: Int = 12
    val layoutCols: Int = math.pow(2, zoom).toInt
    val layoutRows: Int = layoutCols / 2
    val layoutDefinition = LayoutDefinition(crs.worldExtent,
      TileLayout(layoutCols, layoutRows, 256, 256))

    val targetMetadata = tileRDD.collectMetadata[SpatialKey](layoutDefinition)
    val tiledRdd = tileRDD.tileToLayout(targetMetadata)

    val writer = HadoopLayerWriter(pathHadoop)(sc)

    val layerId = LayerId("longitude180", zoom)
    writer.write[SpatialKey, MultibandTile, TileLayerMetadata[SpatialKey]](layerId,
      tiledRdd, ZCurveKeyIndexMethod)
```
And this is the stacktrace:
```
Failed to write Layer(name = "longitude180", zoom = 12)
geotrellis.spark.io.package$LayerWriteError: Failed to write Layer(name = "longitude180", zoom = 12)
	at geotrellis.spark.io.hadoop.HadoopLayerWriter._write(HadoopLayerWriter.scala:118)
	at geotrellis.spark.io.hadoop.HadoopLayerWriter._write(HadoopLayerWriter.scala:39)
	at geotrellis.spark.io.LayerWriter$class.write(LayerWriter.scala:149)
	at geotrellis.spark.io.hadoop.HadoopLayerWriter.write(HadoopLayerWriter.scala:39)
        ...
        ...
Caused by: java.lang.IllegalArgumentException: requirement failed: NOT: 1537228672809260887 < 131813
	at scala.Predef$.require(Predef.scala:224)
	at geotrellis.spark.io.index.zcurve.Z2Range.<init>(Z2Range.scala:29)
	at geotrellis.spark.io.index.zcurve.Z2$.zranges(Z2.scala:103)
	at geotrellis.spark.io.index.zcurve.ZSpatialKeyIndex.indexRanges(ZSpatialKeyIndex.scala:29)
	at geotrellis.spark.io.index.KeyIndex$.breaks(KeyIndex.scala:36)
	at geotrellis.spark.partition.IndexPartitioner.<init>(IndexPartitioner.scala:40)
	at geotrellis.spark.partition.IndexPartitioner$.apply(IndexPartitioner.scala:60)
	at geotrellis.spark.io.hadoop.HadoopRDDWriter$.write(HadoopRDDWriter.scala:222)
	at geotrellis.spark.io.hadoop.HadoopLayerWriter._write(HadoopLayerWriter.scala:120)
```
And this is the tiff file:
[ASTGTM2_N65W180_dem.zip](https://github.com/locationtech/geotrellis/files/2454873/ASTGTM2_N65W180_dem.zip)

**Comment by pomadchin** [comment]
Also I'm wondering, why there is min Longitude is `-180.00014`, can be a precision issues, as it matters for the zoomed layout scheme afaik, as it is a global curve.

**Comment by Frophie** [comment]
@pomadchin Yes, -180.0001389 is TIFF‘s original extent, so we can say this Tiff's coordinates are not normal. Hmm, but I still need to ingest it. And after all, with same layout, `HilbertKeyIndexMethod` is OK.

**Comment by pomadchin** [comment]
Better in terms of precision errors. All our ingest processes are built around it: https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/ingest/Ingest.scala#L75-L96

Can you try to fix the tiff uri and see what would happen? I think ZCruve just overloads as it's out of its max (min) spatial range.

**Comment by pomadchin** [comment]
Closing this issue as evertyhing seems OK. @Frophie feel free to reopen it any time or to create a new issue.
