### ISSUE TITLE
About ETL crs

### ISSUE THREAD

**Issue by lcluowb** [locationtech/geotrellis#2881]
There are 3 errors about reproject while I running ETL.ingest():
1.User guide(https://docs.geotrellis.io/en/latest/guide/etl.html) said that parameter "crs" in output.json is optional, but if I didn't set that, the program will throw an exception as below:
```
Exception in thread "main" java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at geotrellis.spark.etl.Etl.tile(Etl.scala:146)
	at geotrellis.spark.etl.Etl$$anonfun$ingest$1.apply(Etl.scala:70)
	at geotrellis.spark.etl.Etl$$anonfun$ingest$1.apply(Etl.scala:64)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at geotrellis.spark.etl.Etl$.ingest(Etl.scala:64)
	at zju.demo.ETL$.etl(ETL.scala:34)
	at zju.demo.ETL$.main(ETL.scala:72)
	at zju.demo.ETL.main(ETL.scala)
```
2.I have some raster image with EPSG:4326 with extent[-179.91666157804835,-89.91666920862028,179.91669209562647,89.91666920862025] and want to transform it to EPSG:3857,  but get an exception as below:
```
java.lang.RuntimeException: Cannot create a polygon with unclosed exterior: LINESTRING (-20028231.15209407 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 �, -20028231.152094033 -49691199.26708765, -20028231.152094033 -35115580.63185592, -20028231.152094033 -31027532.756571766, -20028231.152094033 -28556262.726534367, -20028231.152094033 -26779464.223368924, -20028231.152094033 -25391189.164381992, -20028231.152094033 -24251592.076807957, -20028231.152094033 -23284928.76859497, -20028231.152094033 -22445524.443135988, -20028231.152094033 -21703701.944829646, -20028231.152094033 -21039085.8984839, -20028231.152094033 -20437080.530246865, -20028231.152094033 -19886871.3700349, -20028231.152094033 -19380222.294386145, -20028231.152094033 -18910715.898620296, -20028231.152094033 -18473254.528801292, -20028231.152094033 -18063721.50057451, -20028231.152094033 -17678744.499773998, -20028231.152094033 -17315526.275950447, -20028231.152094033 -16971720.892644856, -20028231.152094033 -16645341.572586069, -20028231.152094033 -16334690.92636885, -20028231.15209407 -16038307.341672035, -19981666.13370519 -16038307.341672044, -19935101.115316357 -16038307.341672044, -19888536.096927516 -16038307.341672044, -19841971.078538675 -16038307.341672044, -19795406.06014984 -16038307.341672044, -19748841.041761 -16038307.341672044, -19702276.023372166 -16038307.341672044, -19655711.004983325 -16038307.341672044, -19609145.98659437 -16038307.341672044, -19562580.968205538 -16038307.341672044, -19516015.949816696 -16038307.341672044, -19469450.931427862 -16038307.341672044, -19422885.91303902 -16038307.341672044, -19376320.894650184 -16038307.341672044, -19329755.876261346 -16038307.341672044, -19283190.857872505 -16038307.341672044, -19236625.83948367 -16038307.341672044, -19190060.821094718 -16038307.341672044, -19143495.80270588 -16038307.341672044, -19096930.784317043 -16038307.341672044, -19050365.765928205 -16038307.341672044, -19003800.747539368 -16038307.341672044, -18957235.729150526 -16038307.341672044, -18910670.71076169 -16038307.341672044, -18864105.69237285 -16038307.341672044, -18817540.673984013 -16038307.341672044, -18770975.655595176 -16038307.341672044, -18724410.637206223 -16038307.341672044, -18677845.618817385 -16038307.341672044, -18631280.600428548 -16038307.341672044, -18584715.58203971 -16038307.341672044, -18538150.563650873 -16038307.341672044, -18491585.545262035 -16038307.341672044, -18445020.526873197 -16038307.341672044, -18398455.508484356 -16038307.341672044, -18351890.49009552 -16038307.341672044, -18305325.47170668 -16038307.341672044, -18258760.45331773 -16038307.341672044, -18212195.434928894 -16038307.341672044, -18165630.416540053 -16038307.341672044, -18119065.398151215 -16038307.341672044, -18072500.379762378 -16038307.341672044, -18025935.36137354 -16038307.341672044, -17979370.342984702 -16038307.341672044, -17932805.324595865 -16038307.341672044, -17886240.306207024 -16038307.341672044, -17839675.287818186 -16038307.341672044, -17793110.269429237 -16038307.341672044, -17746545.2510404 -16038307.341672044, -17699980.23265156 -16038307.341672044, -17653415.21426274 -16038307.341672035, -17653415.214262724 -16334690.92636885, -17653415.214262724 -16645341.572586069, -17653415.214262724 -16971720.892644856, -17653415.214262724 -17315526.275950447, -17653415.214262724 -17678744.499773998, -17653415.214262724 -18063721.50057451, -17653415.214262724 -18473254.528801292, -17653415.214262724 -18910715.898620296, -17653415.214262724 -19380222.294386145, -17653415.214262724 -19886871.3700349, -17653415.214262724 -20437080.530246865, -17653415.214262724 -21039085.8984839, -17653415.214262724 -21703701.944829646, -17653415.214262724 -22445524.443135988, -17653415.214262724 -23284928.76859497, -17653415.214262724 -24251592.076807957, -17653415.214262724 -25391189.164381992, -17653415.214262724 -26779464.223368924, -17653415.214262724 -28556262.726534367, -17653415.214262724 -31027532.756571766, -17653415.214262724 -35115580.63185592, -17653415.214262724 -49691199.26708765, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.214262724 �, -17653415.21426274 �, -17699980.23265156 �, -17746545.2510404 �, -17793110.269429237 �, -17839675.287818186 �, -17886240.306207024 �, -17932805.324595865 �, -17979370.342984702 �, -18025935.36137354 �, -18072500.379762378 �, -18119065.398151215 �, -18165630.416540053 �, -18212195.434928894 �, -18258760.45331773 �, -18305325.47170668 �, -18351890.49009552 �, -18398455.508484356 �, -18445020.526873197 �, -18491585.545262035 �, -18538150.563650873 �, -18584715.58203971 �, -18631280.600428548 �, -18677845.618817385 �, -18724410.637206223 �, -18770975.655595176 �, -18817540.673984013 �, -18864105.69237285 �, -18910670.71076169 �, -18957235.729150526 �, -19003800.747539368 �, -19050365.765928205 �, -19096930.784317043 �, -19143495.80270588 �, -19190060.821094718 �, -19236625.83948367 �, -19283190.857872505 �, -19329755.876261346 �, -19376320.894650184 �, -19422885.91303902 �, -19469450.931427862 �, -19516015.949816696 �, -19562580.968205538 �, -19609145.98659437 �, -19655711.004983325 �, -19702276.023372166 �, -19748841.041761 �, -19795406.06014984 �, -19841971.078538675 �, -19888536.096927516 �, -19935101.115316357 �, -19981666.13370519 �, -20028231.15209407 �)
	at scala.sys.package$.error(package.scala:27)
	at geotrellis.vector.Polygon$.apply(Polygon.scala:51)
	at geotrellis.vector.reproject.Reproject$.apply(Reproject.scala:59)
	at geotrellis.vector.reproject.Implicits$ReprojectPolygon.reproject(Implicits.scala:53)
	at geotrellis.raster.reproject.ReprojectRasterExtent$.reprojectExtent(ReprojectRasterExtent.scala:52)
	at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:57)
	at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:118)
	at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:121)
	at geotrellis.spark.reproject.TileRDDReproject$$anonfun$matchReprojectRasterExtent$1$$anonfun$14$$anonfun$apply$4$$anonfun$apply$5.apply(TileRDDReproject.scala:365)
	at geotrellis.spark.reproject.TileRDDReproject$$anonfun$matchReprojectRasterExtent$1$$anonfun$14$$anonfun$apply$4$$anonfun$apply$5.apply(TileRDDReproject.scala:363)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:183)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1194)
	at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:206)
	at scala.collection.AbstractIterator.reduce(Iterator.scala:1194)
	at geotrellis.spark.reproject.TileRDDReproject$$anonfun$matchReprojectRasterExtent$1$$anonfun$14$$anonfun$apply$4.apply(TileRDDReproject.scala:373)
	at geotrellis.spark.reproject.TileRDDReproject$$anonfun$matchReprojectRasterExtent$1$$anonfun$14$$anonfun$apply$4.apply(TileRDDReproject.scala:359)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run$$$capture(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
It seems that the symbol � means a null value.
3.And if I try to tile an image in EPSG:3857 with extent[-2.0028231152094074E7,-4.609959765272607E7,2.0031768847905926E7,4.609040234727393E7] to EPSG:3857, I would get these exception:
```
java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:55)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:47)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:244)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.AssertionError: assertion failed: Polygon Empty: POLYGON EMPTY
	at scala.Predef$.assert(Predef.scala:165)
	at geotrellis.vector.Polygon.<init>(Polygon.scala:84)
	at geotrellis.raster.reproject.ReprojectRasterExtent$.reprojectExtent(ReprojectRasterExtent.scala:51)
	at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:57)
	at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:118)
	at geotrellis.raster.reproject.ReprojectRasterExtent$.apply(ReprojectRasterExtent.scala:121)
	at geotrellis.spark.reproject.TileRDDReproject$$anonfun$matchReprojectRasterExtent$1$$anonfun$14$$anonfun$apply$4$$anonfun$apply$5.apply(TileRDDReproject.scala:365)
	at geotrellis.spark.reproject.TileRDDReproject$$anonfun$matchReprojectRasterExtent$1$$anonfun$14$$anonfun$apply$4$$anonfun$apply$5.apply(TileRDDReproject.scala:363)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:370)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:183)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1194)
	at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:206)
	at scala.collection.AbstractIterator.reduce(Iterator.scala:1194)
	at geotrellis.spark.reproject.TileRDDReproject$$anonfun$matchReprojectRasterExtent$1$$anonfun$14$$anonfun$apply$4.apply(TileRDDReproject.scala:373)
	at geotrellis.spark.reproject.TileRDDReproject$$anonfun$matchReprojectRasterExtent$1$$anonfun$14$$anonfun$apply$4.apply(TileRDDReproject.scala:359)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	... 5 more
```
I got exceptions above with version 2.0.0. It looks like that those problem haven't been fixed in latest version. Look forward to your reply.

**Comment by pomadchin** [comment]
Can you provide the full configuration you used and some dataset that can be public to check your case?

**Comment by lcluowb** [comment]
[geotrellis_test.zip](https://github.com/locationtech/geotrellis/files/2976132/geotrellis_test.zip)
I have uploaded my test datas with problem 2 and 3 including 4326.tiff and warp.tiff. Infact, warp.tiff was reprojected from 4326.tiff by a gdal tool named gdalwarp. The program ran in a win10 PC.

**Comment by pomadchin** [comment]
We don't actively support this project anymore and it was moved from this repository. 
The legacy code lives here now https://github.com/geotrellis/spark-etl.

Feel free to reopen this issue if it is still relevant to you somehow.
