### ISSUE TITLE
Rasterizer encountered odd number of X axis intersections for "valid" geometry

### ISSUE THREAD

**Issue by echeipesh** [locationtech/geotrellis#2951]
Sometimes the rasterizer for when `sampleType = PixelIsPoint` fails when it encounters odd number intersections due to oddly shaped holes in polygon.

Error:
```
java.lang.IllegalStateException: Rasterizer encountered an error: an odd number of X axis intersections encountered via a horizontal line across the raster at y = 1464.
```
## Reproduce

Geometry:
```
MULTIPOLYGON (((16.938297271728572 -7.1057114601134685, 16.940380096435604 -7.11311483383173, 16.948240280151424 -7.120201110839844, 16.950801849365234 -7.126163005828914, 16.94946098327648 -7.1346697807310875, 16.95042991638195 -7.144313812255746, 16.953691482544002 -7.152571201324349, 16.96268844604498 -7.157354831695557, 16.968933105468807 -7.163528919219971, 16.97035026550293 -7.170185089111328, 16.968532562255803 -7.1757068634032635, 16.958446502685547 -7.18356466293335, 16.95478820800787 -7.188635826110726, 16.95321846008295 -7.196913242340145, 16.953710556030273 -7.203343868255558, 16.95580101013178 -7.207468986511174, 16.95999526977539 -7.2105870246887775, 16.96826934814453 -7.214764118194523, 16.980268478393555 -7.222060203552189, 16.98859596252447 -7.230751991271973, 16.994888305664176 -7.246803760528508, 17.003946304321232 -7.2633018493651775, 17.004901885986442 -7.2701897621154785, 17.00202178955078 -7.2929449081418625, 17.005510330200195 -7.300049781799089, 17.013101577758732 -7.298867225646973, 17.030548095703182 -7.297869205474797, 17.036788940429744 -7.301269054412899, 17.04057121276861 -7.3143348693848225, 17.045230865478516 -7.32119083404524, 17.051929473876953 -7.325047016143685, 17.060220718383732 -7.325675964355412, 17.06483840942377 -7.327478885650521, 17.076461791992244 -7.342782974243107, 17.091899871826286 -7.344966888427621, 17.09534072875988 -7.343102931976205, 17.103630065918082 -7.343501091003475, 17.10963058471691 -7.3462138175964355, 17.11639976501459 -7.357647895812931, 17.116680145263786 -7.364538192748967, 17.111709594726562 -7.376516819000244, 17.114505767822266 -7.391429901123047, 17.095195770263672 -7.379370212554932, 17.086631774902457 -7.3791069984436035, 17.06407356262207 -7.382655143737622, 17.03965950012207 -7.39322376251198, 17.01720619201666 -7.409928798675594, 16.99250030517578 -7.431678771972656, 16.97617530822754 -7.45312309265131, 16.975658416748104 -7.475382804870378, 16.975421905517578 -7.4984788894651615, 16.974918365478572 -7.526027202606144, 16.971630096435547 -7.547453880310002, 16.96086883544922 -7.57000017166132, 16.935693740844727 -7.5914368629456135, 16.914100646972656 -7.598400115966626, 16.891120910644588 -7.60369682312006, 16.867023468017692 -7.6031508445740315, 16.84569358825695 -7.59926080703741, 16.82435607910162 -7.590648174285889, 16.801898956298885 -7.575075149536133, 16.780273437500057 -7.55311012268055, 16.761413574218807 -7.53086519241333, 16.7453289031983 -7.50723218917841, 16.728412628173828 -7.484713077545109, 16.714267730712834 -7.460524082183724, 16.700401306152457 -7.438282012939396, 16.679344177246094 -7.419105052947941, 16.672128677368164 -7.392967224121094, 16.66435813903803 -7.367942810058651, 16.651060104370117 -7.345150947570744, 16.628627777099553 -7.328200817108154, 16.60675621032709 -7.320153236389103, 16.584884643554688 -7.319605827331543, 16.570341110229492 -7.324855804443359, 16.565496444702262 -7.286251068115234, 16.558296203613565 -7.263457775115796, 16.547775268554744 -7.240387916564941, 16.533933639526367 -7.215379238128719, 16.517881393432788 -7.193704128265324, 16.500997543335018 -7.172306060790959, 16.478858947753906 -7.148965835571289, 16.459209442138956 -7.127292156219426, 16.445377349853516 -7.101725101471004, 16.433773040771484 -7.069768905639648, 16.416347503662053 -7.046708106994629, 16.399757385253963 -7.022256851196232, 16.382335662841854 -6.997806072235107, 16.374608993530387 -6.9758567810058025, 16.353298187255916 -6.965580940246525, 16.331422805786076 -6.96391487121582, 16.306207656860465 -6.972803115844727, 16.283746719360295 -6.993642807006779, 16.26738166809082 -7.014485836029053, 16.249629974365348 -7.036719799041748, 16.227462768554688 -7.043394088745117, 16.205593109130803 -7.028387069702148, 16.183712005615234 -7.022274017333984, 16.16182518005371 -7.021161079406681, 16.14077758789074 -7.008934020996037, 16.119449615478572 -7.0069870948790935, 16.09561157226574 -7.014767169952336, 16.074270248413086 -7.016991138458252, 16.052673339843864 -7.000039100646973, 16.029954910278377 -6.9961462020873455, 16.022815704345817 -6.997577190399113, 16.021642684936523 -6.994476795196476, 16.01226425170904 -6.958073139190674, 16.009244918823242 -6.93528413772583, 16.009828567504996 -6.913887977600041, 16.007091522216797 -6.889155864715519, 16.006294250488338 -6.8666510581970215, 16.00467109680187 -6.844423770904541, 16.001941680908203 -6.819701194763127, 15.99976730346691 -6.796922206878662, 16.000366210937557 -6.774424076080322, 16.000139236450195 -6.7505359649657635, 16.000740051269588 -6.727762222289982, 16.000801086425895 -6.699708938598576, 15.9998197555542 -6.682625770568791, 16.00249290466303 -6.684438228607121, 16.01634979248047 -6.688332080841008, 16.039928436279354 -6.679172992706242, 16.06212043762207 -6.670854091644287, 16.0862274169923 -6.674194812774658, 16.108947753906364 -6.676147937774658, 16.132505416870174 -6.674487113952523, 16.154941558837947 -6.677827835083008, 16.177635192871037 -6.688669204711857, 16.198688507080192 -6.690619945526123, 16.221698760986385 -6.682854175567627, 16.24746894836437 -6.677312850952092, 16.27127838134777 -6.679821968078613, 16.293426513671818 -6.683165073394775, 16.317228317260742 -6.689840793609619, 16.34268760681158 -6.695127964019775, 16.3648357391358 -6.694307804107609, 16.387538909912053 -6.688769817352238, 16.408847808837947 -6.687118053436279, 16.431529998779354 -6.689630985259953, 16.453374862671012 -6.695474147796631, 16.477424621582145 -6.7043681144714355, 16.501482009887752 -6.702165126800537, 16.524145126342887 -6.706902027130127, 16.547615051269645 -6.72717380523676, 16.5713787078858 -6.7352399826049805, 16.5929279327392 -6.733593940734863, 16.616952896118107 -6.7322258949279785, 16.640970230102653 -6.735298156738281, 16.6633243560791 -6.744743824005127, 16.68456459045416 -6.7514209747313885, 16.709108352661133 -6.747273921966553, 16.731430053710994 -6.735911846160832, 16.753747940063477 -6.720635890960693, 16.798795700073356 -6.69401216506958, 16.801031112670955 -6.699099063873291, 16.806350708007812 -6.7031989097595215, 16.811843872070256 -6.705228805541992, 16.81674194335949 -6.709218025207463, 16.822265625000057 -6.710113048553467, 16.8257293701173 -6.713085174560547, 16.82875061035162 -6.719738006591797, 16.83088111877447 -6.7323689460754395, 16.828449249267635 -6.752834796905518, 16.829864501953182 -6.760413646697941, 16.832653045654354 -6.766376972198486, 16.850704193115234 -6.789279937744141, 16.862010955810604 -6.797043800354004, 16.868240356445597 -6.800922870635986, 16.871711730957145 -6.805274963378963, 16.8738174438476 -6.812160015106201, 16.87501716613764 -6.823185920715105, 16.874441146850643 -6.82862186431862, 16.87486839294462 -6.839945793151799, 16.876281738281364 -6.846850872039681, 16.87951850891119 -6.850513935089111, 16.884822845458984 -6.851638793945199, 16.895427703857706 -6.858026981353589, 16.910348892211914 -6.851294994354191, 16.915416717529354 -6.852880954742204, 16.917520523071403 -6.859766006469783, 16.92052650451666 -6.863198757171688, 16.93250465393089 -6.865903854370117, 16.937812805175838 -6.870013236999398, 16.94037055969244 -6.8748288154600345, 16.941810607910384 -6.8879218101501465, 16.9368839263916 -6.915060043334904, 16.943822860717773 -6.921462059020769, 16.947065353393555 -6.930367946624756, 16.945510864257926 -6.938230037689152, 16.945510864257926 -6.939150810241756, 16.940259933471737 -6.946527957916089, 16.937091827392578 -6.957801818847656, 16.938739776611442 -6.966066837310791, 16.9500865936281 -6.980721950531006, 16.961267471313477 -6.981589794158992, 16.963670730590934 -6.98157882690424, 16.969650268554915 -6.982240200042725, 16.972890853881893 -6.9861330986020675, 16.973880767822436 -7.000144958496094, 16.98015785217285 -7.0134439468381515, 16.98274040222168 -7.023312091827279, 16.980930328369084 -7.030213832855225, 16.970874786376953 -7.044045925140381, 16.969306945800838 -7.0525550842285725, 16.970037460327205 -7.060595035552922, 16.970539093017635 -7.069086551666203, 16.96803092956543 -7.074388027190992, 16.963682174682617 -7.078543186187687, 16.960010528564453 -7.0797100067137535, 16.952634811401595 -7.077905178070068, 16.94894027709961 -7.075164794921932, 16.94334983825712 -7.061404228210506, 16.938974380493164 -7.060733795165959, 16.93185997009283 -7.064443111419507, 16.928890228271484 -7.068592071533089, 16.928045272827205 -7.084219932555982, 16.93360137939476 -7.091318130493221, 16.936632156372013 -7.09980487823475, 16.938297271728572 -7.1057114601134685), (16.747369897717057 -6.8236202755392, 16.75614929199213 -6.824551105499324, 16.77772712707531 -6.8262619972229, 16.75614929199213 -6.824551105499268, 16.747369897717057 -6.8236202755392), (16.77772712707531 -6.8262619972229, 16.798490524291992 -6.826418876648006, 16.812221527099666 -6.822111129760799, 16.81947994232182 -6.819354891777024, 16.812221527099666 -6.822111129760742, 16.798490524291992 -6.826418876647949, 16.77772712707531 -6.8262619972229), (16.46659374237062 -7.06616890430449, 16.468503952026367 -7.0653419494629475, 16.483133316040266 -7.063395977020207, 16.487298682074744 -7.061965753463089, 16.483133316040096 -7.063395977020207, 16.468503952026367 -7.065341949462891, 16.46659374237062 -7.06616890430449), (16.522368113199985 -7.037012418111165, 16.52637863159191 -7.032770156860408, 16.530752182006893 -7.022577762603763, 16.52637863159191 -7.032770156860352, 16.522368113199985 -7.037012418111165), (16.543494224548425 -6.961804389953599, 16.54455375671398 -6.957902908325252, 16.544835090637292 -6.953829646110535, 16.54455375671398 -6.957902908325195, 16.543494224548425 -6.961804389953599), (16.545679092407216 -6.941609859466539, 16.539310455322322 -6.934034824371167, 16.5283660888673 -6.928907871246281, 16.539310455322322 -6.934034824371281, 16.545679092407216 -6.941609859466539), (16.516513824462912 -6.918381214141865, 16.518181324005155 -6.915626168251038, 16.51651382446289 -6.918381214141846, 16.516513824462912 -6.918381214141865), (16.548332214355526 -6.894305229186955, 16.554958343506144 -6.881741046905461, 16.558739511977183 -6.874834755268632, 16.554958343505973 -6.881741046905461, 16.548332214355526 -6.894305229186955), (16.572221755981502 -6.862702846527043, 16.582185745239542 -6.8601179122924805, 16.58312622988218 -6.860020322441789, 16.58218574523937 -6.8601179122924805, 16.572221755981502 -6.862702846527043), (16.666481387431823 -6.874223124797468, 16.674222946167276 -6.870077133178768, 16.68477439880388 -6.861287117004281, 16.689179846134213 -6.854903697967441, 16.68477439880371 -6.8612871170043945, 16.674222946167106 -6.870077133178711, 16.666481387431823 -6.874223124797468), (16.697962692950938 -6.844800426943155, 16.70495796203636 -6.838313102722111, 16.716997146606502 -6.827933788299504, 16.70495796203619 -6.838313102722111, 16.697962692950938 -6.844800426943155), (16.730735778808707 -6.823698043823185, 16.74457740783695 -6.823324203491158, 16.744577407836914 -6.823324203491154, 16.730735778808707 -6.823698043823185), (16.842245101928768 -7.070693016052246, 16.85252571105957 -7.080491065978947, 16.86749839782715 -7.093272209167367, 16.876054763794002 -7.09692811965931, 16.88837051391613 -7.098171234130859, 16.902265548706055 -7.101706027984562, 16.8883705139163 -7.098171234130859, 16.876054763794173 -7.09692811965931, 16.86749839782732 -7.093272209167367, 16.85252571105974 -7.080491065978947, 16.842245101928768 -7.070693016052246), (16.667354583740178 -7.195590972900334, 16.67941284179699 -7.1844019889830975, 16.679412841797003 -7.1844019889830735, 16.667354583740178 -7.195590972900334), (16.721696853637695 -7.1188879013060955, 16.722183227539006 -7.108026027679443, 16.722183227539 -7.108026027679402, 16.721696853637695 -7.1188879013060955), (16.757413864135856 -7.068328857421875, 16.773643493652457 -7.0694379806518555, 16.79596519470209 -7.068059921264705, 16.773643493652628 -7.069437980651685, 16.757413864135856 -7.068328857421875)))
```

Steps to reproduce:

```scala
import geotrellis.vector._
import geotrellis.vector.io.wkt.WKT

val str = """<WKT from above>"
val geom = WKT.read(str)
val grid = GridExtent(Extent(15.999750000000006, -7.603750000000005, 17.116749999999996, -6.670749999999998),CellSize(2.5E-4,2.5E-4),4468x3732)

import geotrellis.raster.rasterizer._
Rasterizer.foreachCellByGeometry(geom, grid.toRasterExtent){ (x, y) => Unit }
```

## Visualization

<img width="483" alt="Screen Shot 2019-05-29 at 3 09 51 PM" src="https://user-images.githubusercontent.com/1158084/58585334-73856180-8226-11e9-821d-8b52161adf41.png">
Blue: Geometry
Red: Failing scan line for row 1464

Intersection closeups in order from left to right:
<img width="454" alt="Screen Shot 2019-05-29 at 3 10 02 PM" src="https://user-images.githubusercontent.com/1158084/58585378-8b5ce580-8226-11e9-85d6-8e9afbec6c47.png">
<img width="226" alt="Screen Shot 2019-05-29 at 3 31 02 PM" src="https://user-images.githubusercontent.com/1158084/58585496-e393e780-8226-11e9-85a2-5c878c71c862.png">
<img width="94" alt="Screen Shot 2019-05-29 at 3 31 05 PM" src="https://user-images.githubusercontent.com/1158084/58585498-e55dab00-8226-11e9-8c86-dde9b39b77eb.png">
<img width="537" alt="Screen Shot 2019-05-29 at 3 31 32 PM" src="https://user-images.githubusercontent.com/1158084/58585500-e7276e80-8226-11e9-8e39-33e8b051f843.png">

That middle hole looks weird, it is:
`LINESTRING (16.522368113199985 -7.037012418111165, 16.52637863159191 -7.032770156860408, 16.530752182006893 -7.022577762603763, 16.52637863159191 -7.032770156860352, 16.522368113199985 -7.037012418111165)`

or 

`POLYGON ((16.522368113199985 -7.037012418111165, 16.52637863159191 -7.032770156860352, 16.530752182006893 -7.022577762603763, 16.52637863159191 -7.032770156860408, 16.522368113199985 -7.037012418111165))`

<img width="179" alt="Screen Shot 2019-05-29 at 3 34 50 PM" src="https://user-images.githubusercontent.com/1158084/58585667-51d8aa00-8227-11e9-978c-0117e299f054.png">
square degrees (Geometry is in EPSG:4326)

https://github.com/locationtech/geotrellis/blob/edfc69ea0135b1767f418db9c24d17b72e71ffe1/raster/src/main/scala/geotrellis/raster/rasterize/polygon/PolygonRasterizer.scala#L421-L435

**Comment by jpolchlo** [comment]
This is degenerate geometry, but because we are using a Floating precision model, the degeneracies are allowed to propagate through.  The area of all the interior rings of this geometry are reported in the scala REPL as 0.0.  (The area reported by @echeipesh above is a rounding error away from zero.)

The solution here is to reduce the precision of the geometry.
```scala
import org.locationtech.jts.geom._

val poly: Polygon = ??? // the geometry above
val prec = new PrecisionModel(1e11) // Fixed precision model with 11 decimal places of precision
val reducer = new org.locationtech.jts.precision.GeometryPrecisionReducer(prec)
val reduced = reducer.reduce(poly).asInstanceOf[Polygon]

assert(reduced.getNumInteriorRing == 0)
```

I chose `1e11` above because it was the highest precision that eliminated all interior rings.  And let's be clear that this is _not_ a significant reduction.  It should be unnoticeable in nearly any application.  You may have other geometries that need a slightly lower level of precision to remove these inaccuracies, but it shouldn't be much lower.

The way to deal with this in GT is to make an `application.conf` setting the values shown in https://github.com/locationtech/geotrellis/blob/master/vector/src/main/resources/reference.conf to use a fixed precision model of the desired level.

Following that, you'll need to create a GeometryPrecsionReducer as follows:
```scala
val gpr = new GeometryPrecisionReducer(geotrellis.vector.GeomFactory.precisionModel)
```
(you can validate that your `application.conf` settings took effect by making sure that `GeomFactory.precisionType` is fixed).

Finally, pass your geometries through the following function:
```scala
def reduce(gpr: org.locationtech.jts.precision.GeometryPrecisionReducer)(g: geotrellis.vector.Geometry): geotrellis.vector.Geometry = geotrellis.vector.Geometry(gpr.reduce(g.jtsGeom))
```

**Comment by thomas-maschler** [comment]
@jpolchlo  I tried this
```scala
val gpr = new GeometryPrecisionReducer(geotrellis.vector.GeomFactory.precisionModel)
def reduce(gpr: org.locationtech.jts.precision.GeometryPrecisionReducer)(g: geotrellis.vector.Geometry): geotrellis.vector.Geometry = geotrellis.vector.Geometry(gpr.reduce(g.jtsGeom))

/* Transition from DataFrame to RDD in order to work with GeoTrellis features */
val featureRDD: RDD[Feature[Geometry, GADMFeatureId]] = featuresDF.rdd.map { row: Row =>
              val countryCode: String = row.getString(1)
              val admin1: String = row.getString(2)
              val admin2: String = row.getString(3)
              val geom: Geometry = reduce(gpr)(WKB.read(row.getString(4)))
              Feature(geom, GADMFeatureId(countryCode, admin1, admin2))
            }
```

and got this error:
```
Caused by: java.io.NotSerializableException: org.locationtech.jts.precision.GeometryPrecisionReducer
Serialization stack:
	- object not serializable (class: org.locationtech.jts.precision.GeometryPrecisionReducer, value: org.locationtech.jts.precision.GeometryPrecisionReducer@3656a6cd)
	- field (class: org.globalforestwatch.treecoverloss.TreeLossSummaryMain$$anonfun$$lessinit$greater$1$$anonfun$2, name: gpr$1, type: class org.locationtech.jts.precision.GeometryPrecisionReducer)
	- object (class org.globalforestwatch.treecoverloss.TreeLossSummaryMain$$anonfun$$lessinit$greater$1$$anonfun$2, <function1>)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:400)
	... 26 more
```

**Comment by jpolchlo** [comment]
Hi, @thomas-maschler.  Yes, that is not surprising.  You'll need to reimplement this as a `mapPartitions` instead of a `map`, and create the `GeometryPrecisionReducer` inside the mapping function.  This will avoid the serialization of the unserializable object.

**Comment by thomas-maschler** [comment]
@jpolchlo thanks again for pointing this out. 
To close the loop: 
This approach works for me. The `reduce` function did return some empty geometries for very small features ```java.lang.AssertionError: assertion failed: Polygon Empty: POLYGON EMPTY``` but I was able to catch this.

**Comment by jpolchlo** [comment]
Good to hear!  I'll close this issue up, then.  Feel free to reopen if you need.
