### ISSUE TITLE
Serializing `Multipoint Empty` throws UnsupportedOperationException

### ISSUE THREAD

**Issue by JoelWAnna** [locationtech/geotrellis#3076]
Just upgraded from 1.2.1 to 2.3.1

```scala
import spray.json._
import geotrellis.vector.io.json.GeometryFormats._
import geotrellis.vector.io.wkt.WKT

WKT.read("MULTIPOINT EMPTY").toJson
```

stack trace

```
java.lang.UnsupportedOperationException: empty.reduceLeft
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:180)
	at scala.collection.AbstractTraversable.reduceLeft(Traversable.scala:104)
	at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
	at scala.collection.AbstractTraversable.reduce(Traversable.scala:104)
	at geotrellis.vector.Geometry$class.vertices(Geometry.scala:80)
	at geotrellis.vector.MultiPoint.vertices$lzycompute(MultiPoint.scala:51)
	at geotrellis.vector.MultiPoint.vertices(MultiPoint.scala:51)
	at geotrellis.vector.MultiPoint.points$lzycompute(MultiPoint.scala:62)
	at geotrellis.vector.MultiPoint.points(MultiPoint.scala:62)
	at geotrellis.vector.io.json.GeometryFormats$MultiPointFormat$.write(GeometryFormats.scala:155)
	at geotrellis.vector.io.json.GeometryFormats$MultiPointFormat$.write(GeometryFormats.scala:144)
	at spray.json.RichAny.toJson(package.scala:44)
	at geotrellis.vector.io.json.GeometryFormats$GeometryFormat$.write(GeometryFormats.scala:221)
	at geotrellis.vector.io.json.GeometryFormats$GeometryFormat$.write(GeometryFormats.scala:214)
	at spray.json.RichAny.toJson(package.scala:44)
```

**Comment by pomadchin** [comment]
It is fixed in the current master branch: 

```scala
import io.circe._
import io.circe.syntax._
import geotrellis.vector._
import geotrellis.vector.io._
import geotrellis.vector.io.json._
import geotrellis.vector.io.wkt.WKT

WKT.read("MULTIPOINT EMPTY").asJson //> {
//   "type" : "MultiPoint",
//   "coordinates" : [
//   ]
// }
```

We don't plan to fix it in 2.x versions, however, you're welcome to create a PR with fix and we'll cut down a release for you! Feel free to reopen this issue.
