### ISSUE TITLE
GeoTiff read failure with missing TIFFTAG_STRIPBYTECOUNTS tag

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#3141]
We had a case when GDAL could properly handle a stripedtiff with a missing [TIFFTAG_STRIPBYTECOUNTS](https://www.awaresystems.be/imaging/tiff/tifftags/stripbytecounts.html) tag. In TIFF docs it is mentioned that it is a _required_ field, however GDAL knows how to hanlde it.

The following excpetion would be thrown during such a tiff read:

https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/io/geotiff/tags/TiffTags.scala#L549-L557

```
geotrellis.raster.io.geotiff.reader.MalformedGeoTiffException: No StripByteCount information.
    at geotrellis.raster.io.geotiff.tags.TiffTags.segmentCount(TiffTags.scala:556)
    at geotrellis.raster.io.geotiff.compression.Decompressor$.apply(Decompressor.scala:96)
    at 
geotrellis.raster.io.geotiff.reader.GeoTiffInfo$.getGeoTiffInfo$1(GeoTiffInfo.scala:179)
```

**Comment by pomadchin** [comment]
Potentially fixed by https://github.com/locationtech/geotrellis/pull/3557
