### ISSUE TITLE
object not serializable exception when passing s3client to S3GeoTiffRDD.Options.

### ISSUE THREAD

**Issue by irhawks** [locationtech/geotrellis#3173]
geotrellis: 3.2.0
scala: 2.12
spark: 2.4.4
sbt: 1.3.4

S3GeoTiffRDD.spatial works properly when code is wrapped in a scala app below, but it raises serialization error after explicitly define a `main` method for an object. I tried to solve serialization error by wrap s3 client in a separate object, but the program still throws exception.

```scala
object GeotiffIngester extends App {
  ...
  val client = { 
        val httpClient = ApacheHttpClient.builder().build()
        val provider = ProfileCredentialsProvider.builder.build()
        S3Client.builder
        .endpointOverride(new URI(cli.s3_endpoint))
        .credentialsProvider(provider)
        .region(Region.US_EAST_1)
        .httpClient(httpClient)
        .build()
  }
  val rawTiff: RDD[(ProjectedExtent, Tile)] = S3GeoTiffRDD.spatial(
      cli.bucket,
      cli.tiff_path,
      S3GeoTiffRDD.Options(getClient = { () => client})
    )   
}
```

But spark throws java.io.NotSerializableException after rewrite main entrypoint:

```scala
object GeotiffIngester {
  def main(args: Array[String]) = {
     ....
       val client = { 
        val httpClient = ApacheHttpClient.builder().build()
        val provider = ProfileCredentialsProvider.builder.build()
        S3Client.builder
        .endpointOverride(new URI(cli.s3_endpoint))
        .credentialsProvider(provider)
        .region(Region.US_EAST_1)
        .httpClient(httpClient)
        .build()
  }
  val rawTiff: RDD[(ProjectedExtent, Tile)] = S3GeoTiffRDD.spatial(
      cli.bucket,
      cli.tiff_path,
      S3GeoTiffRDD.Options(getClient = { () => client})
    )   
  }
}
```

I tried to wrap s3client into an object like  #3077, and  #3059, like this

```scala
object GeotiffIngester {
  def main(args: Array[String]) = {
     ....
    object S3ClientProducer {
      @transient private lazy val client = {
        val httpClient = ApacheHttpClient.builder().build()
        val provider = ProfileCredentialsProvider.builder.build()
        S3Client.builder
        .endpointOverride(new URI(cli.s3_endpoint))
        .credentialsProvider(provider)
        .region(Region.US_EAST_1)
        .httpClient(httpClient)
        .build()
      }
      private var summonClient: () => S3Client = { () => client }
      def set(getClient: () => S3Client): Unit = 
        summonClient = getClient
      def get: () => S3Client = summonClient 
    }
    
    // Generate a tiff reader from S3 connection
    val rawTiff: RDD[(ProjectedExtent, Tile)] = S3GeoTiffRDD.spatial(
      cli.bucket,
      cli.tiff_path,
      S3GeoTiffRDD.Options(getClient = { () => S3ClientProducer.get() })
    )
  }
}
```

then get this error:

```text
20/01/01 09:52:47 INFO ContextHandler: Started o.s.j.s.ServletContextHandler@3a80515c{/metrics/json,null,AVAILABLE,@Spark}
Exception in thread "main" org.apache.spark.SparkException: Task not serializable
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:403)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:393)
	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
	at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
	at org.apache.spark.rdd.RDD.$anonfun$flatMap$1(RDD.scala:380)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.flatMap(RDD.scala:379)
	at geotrellis.spark.store.s3.S3GeoTiffInfoReader.geoTiffInfoRDD(S3GeoTiffInfoReader.scala:68)
	at geotrellis.spark.store.s3.S3GeoTiffRDD$.apply(S3GeoTiffRDD.scala:155)
	at geotrellis.spark.store.s3.S3GeoTiffRDD$.apply(S3GeoTiffRDD.scala:191)
	at geotrellis.spark.store.s3.S3GeoTiffRDD$.apply(S3GeoTiffRDD.scala:203)
	at geotrellis.spark.store.s3.S3GeoTiffRDD$.singleband(S3GeoTiffRDD.scala:224)
	at geotrellis.spark.store.s3.S3GeoTiffRDD$.spatial(S3GeoTiffRDD.scala:266)
	at com.irhawks.geotrellis.tiler.GeotiffIngester$.runWithCli(GeotrellisIngester.scala:145)
	at com.irhawks.geotrellis.tiler.GeotiffIngester$.main(GeotrellisIngester.scala:103)
	at com.irhawks.geotrellis.tiler.GeotiffIngester.main(GeotrellisIngester.scala)
Caused by: java.io.NotSerializableException: com.irhawks.geotrellis.tiler.GeotiffIngester$
Serialization stack:
	- object not serializable (class: com.irhawks.geotrellis.tiler.GeotiffIngester$, value: com.irhawks.geotrellis.tiler.GeotiffIngester$@546e61d5)
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 3)
	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class com.irhawks.geotrellis.tiler.GeotiffIngester$, functionalInterfaceMethod=scala/Function0.apply:()Ljava/lang/Object;, implementation=invokeStatic com/irhawks/geotrellis/tiler/GeotiffIngester$.$anonfun$runWithCli$1:(Lcom/irhawks/geotrellis/tiler/GeotiffIngester$;Lscala/runtime/LazyRef;Lcom/irhawks/geotrellis/tiler/CliArguments;)Lsoftware/amazon/awssdk/services/s3/S3Client;, instantiatedMethodType=()Lsoftware/amazon/awssdk/services/s3/S3Client;, numCaptured=3])
	- writeReplace data (class: java.lang.invoke.SerializedLambda)
	- object (class com.irhawks.geotrellis.tiler.GeotiffIngester$$$Lambda$522/474933596, com.irhawks.geotrellis.tiler.GeotiffIngester$$$Lambda$522/474933596@6944e53e)
	- field (class: geotrellis.spark.store.s3.S3GeoTiffRDD$Options, name: getClient, type: interface scala.Function0)
	- object (class geotrellis.spark.store.s3.S3GeoTiffRDD$Options, Options(List(.tif, .TIF, .tiff, .TIFF),None,TIFFTAG_DATETIME,yyyy:MM:dd HH:mm:ss,Some(256),None,Some(134217728),None,None,com.irhawks.geotrellis.tiler.GeotiffIngester$$$Lambda$522/474933596@6944e53e))
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 1)
	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class geotrellis.spark.store.s3.S3GeoTiffInfoReader$, functionalInterfaceMethod=scala/Function0.apply:()Ljava/lang/Object;, implementation=invokeStatic geotrellis/spark/store/s3/S3GeoTiffInfoReader$.$anonfun$apply$1:(Lgeotrellis/spark/store/s3/S3GeoTiffRDD$Options;)Lsoftware/amazon/awssdk/services/s3/S3Client;, instantiatedMethodType=()Lsoftware/amazon/awssdk/services/s3/S3Client;, numCaptured=1])
	- writeReplace data (class: java.lang.invoke.SerializedLambda)
	- object (class geotrellis.spark.store.s3.S3GeoTiffInfoReader$$$Lambda$524/800493254, geotrellis.spark.store.s3.S3GeoTiffInfoReader$$$Lambda$524/800493254@58ff8d79)
	- field (class: geotrellis.spark.store.s3.S3GeoTiffInfoReader, name: s3Client, type: interface scala.Function0)
	- object (class geotrellis.spark.store.s3.S3GeoTiffInfoReader, geotrellis.spark.store.s3.S3GeoTiffInfoReader@62e93c3a)
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 1)
```

**Comment by irhawks** [comment]
error information:

```text
Caused by: java.io.NotSerializableException: com.irhawks.geotrellis.tiler.GeotiffIngester$
Serialization stack:
	- object not serializable (class: com.irhawks.geotrellis.tiler.GeotiffIngester$, value: com.irhawks.geotrellis.tiler.GeotiffIngester$@5bc7e78e)
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 3)
	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class com.irhawks.geotrellis.tiler.GeotiffIngester$, functionalInterfaceMethod=scala/Function0.apply:()Ljava/lang/Object;, implementation=invokeStatic com/irhawks/geotrellis/tiler/GeotiffIngester$.$anonfun$runWithCli$1:(Lcom/irhawks/geotrellis/tiler/GeotiffIngester$;Lscala/runtime/LazyRef;Lcom/irhawks/geotrellis/tiler/CliArguments;)Lsoftware/amazon/awssdk/services/s3/S3Client;, instantiatedMethodType=()Lsoftware/amazon/awssdk/services/s3/S3Client;, numCaptured=3])
	- writeReplace data (class: java.lang.invoke.SerializedLambda)
	- object (class com.irhawks.geotrellis.tiler.GeotiffIngester$$$Lambda$521/274100821, com.irhawks.geotrellis.tiler.GeotiffIngester$$$Lambda$521/274100821@61cd1c71)
	- field (class: geotrellis.spark.store.s3.S3GeoTiffRDD$Options, name: getClient, type: interface scala.Function0)
	- object (class geotrellis.spark.store.s3.S3GeoTiffRDD$Options, Options(List(.tif, .TIF, .tiff, .TIFF),None,TIFFTAG_DATETIME,yyyy:MM:dd HH:mm:ss,Some(256),None,Some(134217728),None,None,com.irhawks.geotrellis.tiler.GeotiffIngester$$$Lambda$521/274100821@61cd1c71))
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 1)
	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class geotrellis.spark.store.s3.S3GeoTiffInfoReader$, functionalInterfaceMethod=scala/Function0.apply:()Ljava/lang/Object;, implementation=invokeStatic geotrellis/spark/store/s3/S3GeoTiffInfoReader$.$anonfun$apply$1:(Lgeotrellis/spark/store/s3/S3GeoTiffRDD$Options;)Lsoftware/amazon/awssdk/services/s3/S3Client;, instantiatedMethodType=()Lsoftware/amazon/awssdk/services/s3/S3Client;, numCaptured=1])
	- writeReplace data (class: java.lang.invoke.SerializedLambda)
	- object (class geotrellis.spark.store.s3.S3GeoTiffInfoReader$$$Lambda$523/1227867806, geotrellis.spark.store.s3.S3GeoTiffInfoReader$$$Lambda$523/1227867806@292158f8)
	- field (class: geotrellis.spark.store.s3.S3GeoTiffInfoReader, name: s3Client, type: interface scala.Function0)
	- object (class geotrellis.spark.store.s3.S3GeoTiffInfoReader, geotrellis.spark.store.s3.S3GeoTiffInfoReader@4110765e)
	- element of array (index: 0)
	- array (class [Ljava.lang.Object;, size 1)
	- field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
	- object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class geotrellis.spark.store.s3.S3GeoTiffInfoReader, functionalInterfaceMethod=scala/Function1.apply:(Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic geotrellis/spark/store/s3/S3GeoTiffInfoReader.$anonfun$geoTiffInfoRDD$2:(Lgeotrellis/spark/store/s3/S3GeoTiffInfoReader;Ljava/lang/String;)Lscala/collection/TraversableOnce;, instantiatedMethodType=(Ljava/lang/String;)Lscala/collection/TraversableOnce;, numCaptured=1])
	- writeReplace data (class: java.lang.invoke.SerializedLambda)
	- object (class geotrellis.spark.store.s3.S3GeoTiffInfoReader$$Lambda$934/916897446, geotrellis.spark.store.s3.S3GeoTiffInfoReader$$Lambda$934/916897446@7899de11)
	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:41)
	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:46)
	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:100)
	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:400)
	... 17 more
20/01/01 10:03:51 INFO SparkContext: Invoking stop() from shutdown hook
20/01/01 10:03:51 INFO AbstractConnector: Stopped Spark@6eeade6c{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
20/01/01 10:03:51 INFO SparkUI: Stopped Spark web UI at http://10.0.0.254:4040
```

**Comment by pomadchin** [comment]
Hey! I didn’t love close enough into it, but define all objects that may be serilalized outside of the main function definition.

**Comment by irhawks** [comment]
It works!
