### ISSUE TITLE
`GridExtent.combine` has conflict with the require() in GridExtent's Constructor

### ISSUE THREAD

**Issue by Frophie** [locationtech/geotrellis#3198]
Try this test code:
```
      val geA = GridExtent[Int](Extent(45.918, 97.646, 63.918, 118.646), CellSize(1.0, 1.0))
      val geB = GridExtent[Int](Extent(63.918, 97.646, 109.304, 118.646), CellSize(1.0, 1.0))

      val combinedExtent = geA combine geB
```
will get:
```
requirement failed: Extent(45.918, 97.646, 109.304, 118.646) at CellSize(1.0,1.0) does not match 64x21
java.lang.IllegalArgumentException: requirement failed: Extent(45.918, 97.646, 109.304, 118.646) at CellSize(1.0,1.0) does not match 64x21
	at scala.Predef$.require(Predef.scala:224)
	at geotrellis.raster.GridExtent.<init>(GridExtent.scala:45)
	at geotrellis.raster.GridExtent.combine(GridExtent.scala:76)
	at geotrellis.raster.GridExtent.combine$mcI$sp(GridExtent.scala:66)
```

Turns out this [ceil](https://github.com/locationtech/geotrellis/blob/4518b56c7a1dffbb85a3318199633d15e21426ef/raster/src/main/scala/geotrellis/raster/GridExtent.scala#L73) and this [round](https://github.com/locationtech/geotrellis/blob/4518b56c7a1dffbb85a3318199633d15e21426ef/raster/src/main/scala/geotrellis/raster/GridExtent.scala#L46) are in conflict.

I guess we should change the `round` in the require() to `ceil`. (And change [this `round`](https://github.com/locationtech/geotrellis/blob/4518b56c7a1dffbb85a3318199633d15e21426ef/raster/src/main/scala/geotrellis/raster/GridExtent.scala#L56) to `ceil` together.)

There are same problem in `GridExtent.withResolution`.

I met this issue when trying to use `MosaicRasterSource`.

**Comment by pomadchin** [comment]
Thanks for your report @Frophie 
definitely looks like a bug
