### ISSUE TITLE
HadoopGeoTiffReader.readMultiband() with large GeoTiff file

### ISSUE THREAD

**Issue by santocp94** [locationtech/geotrellis#3199]
Trying to read a large GeoTiff file within this way:

```
implicit val sc : SparkContext = ???

val tiffComplete: MultibandGeoTiff = HadoopGeoTiffReader.readMultiband(new Path("path_to_file"))
```

or this:

```
implicit val sc : SparkContext = ???

HadoopGeoTiffReader
  .readMultiband(
    new Path("path_to_file”), 
    streaming = true, 
    None, 
    sc.hadoopConfiguration
  )
```

produces this error:
```User class threw exception: java.lang.NegativeArraySizeException
java.lang.NegativeArraySizeException
        at org.apache.commons.io.output.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:367)
        at org.apache.commons.io.IOUtils.toByteArray(IOUtils.java:766)
        at geotrellis.spark.io.hadoop.HadoopGeoTiffReader$$anonfun$readMultiband$1.apply(HadoopGeoTiffReader.scala:42)
        at geotrellis.spark.io.hadoop.HadoopGeoTiffReader$$anonfun$readMultiband$1.apply(HadoopGeoTiffReader.scala:41)
        at geotrellis.spark.io.hadoop.HdfsUtils$.read(HdfsUtils.scala:280)
        at geotrellis.spark.io.hadoop.HadoopGeoTiffReader$.readMultiband(HadoopGeoTiffReader.scala:41)
        at Main$.delayedEndpoint$Main$1(Main.scala:69)
        at Main$delayedInit$body.apply(Main.scala:16)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at Main$.main(Main.scala:16)
        at Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:667)```

**Comment by pomadchin** [comment]
Thanks for a bug report!
