### ISSUE TITLE
About GeoTiffReader reading tif exception

### ISSUE THREAD

**Issue by wenjunzhangp** [locationtech/geotrellis#3282]
I encountered an exception when using `GeoTiffReader` to read the `tif` file. I don’t understand this very well.
this is my code:

```
val tiff = CachingGeoTiffReader[MultibandTile].cacheRead(path)

implicit val cachingSinglebandReader: CachingGeoTiffReader[Tile] = new CachingGeoTiffReader[Tile] {
    def cacheRead(uri: String): GeoTiff[Tile] = {
      getLocalCache[Tile].getOrElseUpdate(uri, () => read(uri, true))
    }

    def read(byteReader: ByteReader, streaming: Boolean): GeoTiff[Tile] = {
      GeoTiffReader.readSingleband(byteReader, streaming)
    }
  }

  implicit val cachingMultibandReader: CachingGeoTiffReader[MultibandTile] = new CachingGeoTiffReader[MultibandTile] {
    def cacheRead(uri: String): GeoTiff[MultibandTile] = {
      getLocalCache[MultibandTile].getOrElseUpdate(uri, () => read(uri, streaming = true))
    }

    def read(byteReader: ByteReader, streaming: Boolean): GeoTiff[MultibandTile] = {
      GeoTiffReader.readMultiband(byteReader, streaming)
    }
  }

  def apply[V <: CellGrid[scala.Int]](implicit ev: CachingGeoTiffReader[V]): CachingGeoTiffReader[V] = ev
}

trait CachingGeoTiffReader[V <: CellGrid[scala.Int]] extends GeoTiffReader[V] {
  def cacheRead(uri: String): GeoTiff[V]
}
```

After this code is executed, I will get an exception error, roughly as follows:

```
20/08/13 16:55:41 ERROR [dispatcherServlet]: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is geotrellis.raster.io.geotiff.reader.MalformedGeoTiffException: Bad PlanarConfiguration tag: 256] with root cause
geotrellis.raster.io.geotiff.reader.MalformedGeoTiffException: Bad PlanarConfiguration tag: 256
	at geotrellis.raster.io.geotiff.tags.TiffTags.interleaveMethod(TiffTags.scala:139)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.getGeoTiffInfo$1(GeoTiffReader.scala:390)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.$anonfun$readGeoTiffInfo$2(GeoTiffReader.scala:471)
	at scala.collection.immutable.List.map(List.scala:286)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readGeoTiffInfo(GeoTiffReader.scala:471)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readMultiband(GeoTiffReader.scala:219)
	at geotrellis.raster.io.geotiff.reader.GeoTiffReader$.readMultiband(GeoTiffReader.scala:206)
	at cn.hthj.rss.cache.CachingGeoTiffReader$$anon$2.read(CachingGeoTiffReader.scala:39)
	at cn.hthj.rss.cache.CachingGeoTiffReader$$anon$2.$anonfun$cacheRead$2(CachingGeoTiffReader.scala:35)
	at cn.hthj.rss.cache.Cache.getOrElseUpdate(Cache.scala:14)
	at cn.hthj.rss.cache.CachingGeoTiffReader$$anon$2.cacheRead(CachingGeoTiffReader.scala:35)
	at cn.hthj.rss.service.impl.CropServiceImpl.immediatelyCrop(CropServiceImpl.scala:137)
	at cn.hthj.rss.controller.QueryController.immediatelyCrop(QueryController.scala:48)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

How can I solve this error? I tried a lot of tif files and got this error without `exception`.

These `tif` files of mine are all converted by `geotrellis`, the code is as follows:

```
val tiff = GeoTiffRasterSource(path).tiff
      tiff
        .withOverviews(NearestNeighbor, List(2, 4, 8, 16, 32))
        .copy(options = tiff.options.copy(storageMethod = Tiled(256, 256)))
        .write("/usr/local/web/rssdata/wenjunzhangp.tif")
```

Once these `tif` files are converted by the above code, and then read with `GeoTiffReader`, an error will be reported.

**Comment by pomadchin** [comment]
Hi @wenjunzhangp do you have that tiff available somewhere? 
What GeoTrellis version do you use? 

Does it constantly fails or only in a multihreaded environment? 
What is the `getLocalCache` function? Can you provide a code sample that can be compiled? (you can put the code into https://scastie.scala-lang.org/ just to check that it can be compiled)

P.S. We also have a bug report template that could work for this type of questions.

Thanks

**Comment by wenjunzhangp** [comment]
The version of geotrellis I use is 3.0.0-M3.

`getLocalCache` function:

```
private def getLocalCache[V <: CellGrid[scala.Int]](implicit cache: ThreadLocal[Cache[V]]): Cache[V] = {
    cache.get match {
      case c: Cache[V] => c
      case _ => val lc = Cache[V](maxCacheSize); cache.set(lc); lc
    }
  }
```

CachingGeoTiffReader class code:

```
package cn.hthj.rss.cache

import geotrellis.raster.io.geotiff.GeoTiff
import geotrellis.raster.io.geotiff.reader.GeoTiffReader
import geotrellis.raster.{CellGrid, MultibandTile, Tile}
import geotrellis.util.{ByteReader, FileRangeReader, StreamingByteReader}

object CachingGeoTiffReader {
  private val maxCacheSize = 100

  private implicit val singlebandCache: ThreadLocal[Cache[Tile]] = new ThreadLocal[Cache[Tile]]()
  private implicit val multibandCache: ThreadLocal[Cache[MultibandTile]] = new ThreadLocal[Cache[MultibandTile]]()

  implicit def getByteReader(uri: String): StreamingByteReader = StreamingByteReader(FileRangeReader(uri))

  private def getLocalCache[V <: CellGrid[scala.Int]](implicit cache: ThreadLocal[Cache[V]]): Cache[V] = {
    cache.get match {
      case c: Cache[V] => c
      case _ => val lc = Cache[V](maxCacheSize); cache.set(lc); lc
    }
  }

  implicit val cachingSinglebandReader: CachingGeoTiffReader[Tile] = new CachingGeoTiffReader[Tile] {
    def cacheRead(uri: String): GeoTiff[Tile] = {
      getLocalCache[Tile].getOrElseUpdate(uri, () => read(uri, true))
    }

    def read(byteReader: ByteReader, streaming: Boolean): GeoTiff[Tile] = {
      GeoTiffReader.readSingleband(byteReader, streaming)
    }
  }

  implicit val cachingMultibandReader: CachingGeoTiffReader[MultibandTile] = new CachingGeoTiffReader[MultibandTile] {
    def cacheRead(uri: String): GeoTiff[MultibandTile] = {
      getLocalCache[MultibandTile].getOrElseUpdate(uri, () => read(uri, streaming = true))
    }

    def read(byteReader: ByteReader, streaming: Boolean): GeoTiff[MultibandTile] = {
      GeoTiffReader.readMultiband(byteReader, streaming)
    }
  }

  def apply[V <: CellGrid[scala.Int]](implicit ev: CachingGeoTiffReader[V]): CachingGeoTiffReader[V] = ev
}

trait CachingGeoTiffReader[V <: CellGrid[scala.Int]] extends GeoTiffReader[V] {
  def cacheRead(uri: String): GeoTiff[V]
}
```

**Comment by wenjunzhangp** [comment]
@pomadchin @atararaksin Thank you very much for your guidance, it is very helpful to me~
I have tried the branch of `gdal-raster-source`, but because I am in China, many resource jar packages cannot be downloaded, and the project has not been able to run. Maybe I can delve into [this branch](https://github.com/atararaksin/cog-tile-server/tree/gdal-raster-source) and try to solve the problem of resource dependency packages.
