### ISSUE TITLE
Tests regression after the proj4j 1.1.4 upgrade

### ISSUE THREAD

**Issue by pomadchin** [locationtech/geotrellis#3454]
## Describe the bug

```
github-test-1  | [info] OverzoomingValueReaderSpec:
github-test-1  | [info] OverzoomingValueReader
github-test-1  | [info] - should work for simple case *** FAILED *** (101 milliseconds)
github-test-1  | [info]   java.lang.NullPointerException:
github-test-1  | [info]   at org.locationtech.proj4j.datum.Grid.equals(Grid.java:393)
github-test-1  | [info]   at java.util.AbstractList.equals(AbstractList.java:523)
github-test-1  | [info]   at org.locationtech.proj4j.datum.Datum.isEqual(Datum.java:205)
github-test-1  | [info]   at org.locationtech.proj4j.CoordinateReferenceSystem.equals(CoordinateReferenceSystem.java:134)
github-test-1  | [info]   at geotrellis.proj4.CRS.equals(CRS.scala:161)
github-test-1  | [info]   at geotrellis.proj4.CRS.equals$(CRS.scala:159)
github-test-1  | [info]   at geotrellis.proj4.WebMercator$.equals(WebMercator.scala:21)
github-test-1  | [info]   at geotrellis.layer.package$CRSWorldExtent$.worldExtent$extension(package.scala:61)
github-test-1  | [info]   at geotrellis.layer.ZoomedLayoutScheme.levelForZoom(ZoomedLayoutScheme.scala:104)
github-test-1  | [info]   at geotrellis.store.OverzoomingValueReader$$anon$1.<init>(OverzoomingValueReader.scala:39)
github-test-1  | [info]   ...
```

This could be the proj4j regression or the GT misbehavior. It was revealed here: https://github.com/locationtech/geotrellis/pull/3452

**Comment by pomadchin** [comment]
Closed via https://github.com/locationtech/proj4j/pull/78 and is used here https://github.com/locationtech/geotrellis/pull/3452
