### ISSUE TITLE
After merge rdd, regrid get wrong row / col info

### ISSUE THREAD

**Issue by imperio-wxm** [locationtech/geotrellis#3468]
## Describe the bug

Regrid operation after merging two `MultibandTileLayerRDD[K]`, get Row/Col error message

## To Reproduce

- Download data
[LC08_L2SP_126032_20220408_20220412_02_T1_SR_B2.TIF](https://dds.cr.usgs.gov/download/eyJpZCI6MTgxODc5NTg4LCJjb250YWN0SWQiOjI2MTkyOTg5fQ==/)
[LC08_L2SP_126033_20220408_20220412_02_T1_SR_B2.TIF](https://dds.cr.usgs.gov/download/eyJpZCI6MTgxOTQ2MjA5LCJjb250YWN0SWQiOjI2MTkyOTg5fQ==/)

> Full unit test
```scala
// There is no business logic of my own in this code, it is completely geotrells own api implementation.

it("merge rdd") {
    def genSourceRddWrapper(sc: SparkContext, files: Seq[String], targetCRS: CRS, layoutScheme: LayoutScheme) = {
        val sourceRDD: RDD[RasterSource] = sc.parallelize(files)
            .map(uri => {
            if (Objects.nonNull(targetCRS)) {
                GeoTiffRasterSource(uri).reproject(targetCRS): RasterSource
            } else {
                GeoTiffRasterSource(uri): RasterSource
            }
            })
        val summary = RasterSummary.fromRDD(sourceRDD)
        val LayoutLevel(zoom, layout2) = summary.levelFor(layoutScheme)
        RasterSourceRDD.tiledLayerRDD(sourceRDD, layout2, KeyExtractor.spatialKeyExtractor, rasterSummary = Some(summary))
    }

    val image1 = "/Downloads/LC08_L2SP_126032_20220408_20220412_02_T1_SR_B2.TIF"
    val image2 = "/Downloads/LC08_L2SP_126033_20220408_20220412_02_T1_SR_B2.TIF"

    val rdd1 = genSourceRddWrapper(sparkContext, Seq(image1), WebMercator, FloatingLayoutScheme(512))
    val rdd2 = genSourceRddWrapper(sparkContext, Seq(image2), WebMercator, FloatingLayoutScheme(512))
    
    val resultRdd = rdd1.merge(rdd2)
    
    resultRdd.regrid(1024).toGeoTiffs().foreach {
        case (key, mTile) =>
            val localPath = s"/Downloads/merge_$key.tif"
            GeoTiffWriter.write(MultibandGeoTiff(mTile.tile, mTile.extent, mTile.crs), localPath, optimizedOrder = true)
    }
}
```

> Get error

```scala
22/06/27 11:38:52 ERROR Executor: Exception in task 0.0 in stage 7.0 (TID 7)
java.lang.AssertionError: assertion failed: Row/col intervals must begin before they end
	at scala.Predef$.assert(Predef.scala:219)
	at geotrellis.spark.regrid.Regrid$Interval.<init>(Regrid.scala:34)
	at geotrellis.spark.regrid.Regrid$Interval.intersect(Regrid.scala:38)
	at geotrellis.spark.regrid.Regrid$.$anonfun$apply$6(Regrid.scala:119)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at geotrellis.spark.regrid.Regrid$.$anonfun$apply$4(Regrid.scala:111)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.Iterator.foreach(Iterator.scala:944)
	at scala.collection.Iterator.foreach$(Iterator.scala:944)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at geotrellis.spark.regrid.Regrid$.$anonfun$apply$2(Regrid.scala:106)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:482)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:488)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:498)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

## Screenshots

> Before merge

LC08_L2SP_126032_20220408_20220412_02_T1_SR_B2.TIF Metadata
![image](https://user-images.githubusercontent.com/8111349/175862633-d6fa0507-9d17-4159-968f-28da4d8d460e.png)

LC08_L2SP_126033_20220408_20220412_02_T1_SR_B2.TIF Metadata
![image](https://user-images.githubusercontent.com/8111349/175862733-bff79289-94db-43ff-9316-3c97e08ae69d.png)

> After merge

![image](https://user-images.githubusercontent.com/8111349/175862769-fef291a8-5653-436d-aaa1-ea9c7dc8fd06.png)

After the merge, the values ​​of cols and rows of the layout are still the previous values, and have not changed, which is very strange.

## Environment

- Java version: 1.8
- Scala version: 2.12.15
- GeoTrellis version: 3.6.2

**Comment by pomadchin** [comment]
hey @imperio-wxm read the example #2:

```scala
it("merge rdd (behaves in fact like above, but manually and slower)") {
  val image1 = "/Users/.../Downloads/LC08_L2SP_126032_20220408_20220412_02_T1_SR_B2.TIF"
  val image2 = "/Users/.../Downloads/LC08_L2SP_126033_20220408_20220412_02_T1_SR_B2.TIF"

  val layoutScheme = FloatingLayoutScheme(512)

  // read raster1
  val source1: RDD[RasterSource] = sparkContext.parallelize(image1 :: Nil).map { RasterSource(_).reproject(WebMercator): RasterSource }
  // read raster2
  val source2: RDD[RasterSource] = sparkContext.parallelize(image2 :: Nil).map { RasterSource(_).reproject(WebMercator): RasterSource }

  // collect summaries 
  val summary1 = RasterSummary.fromRDD(source1)
  val summary2 = RasterSummary.fromRDD(source2)

  // combine summaries
  val summary = summary1.combine(summary2)
  // get the unified layout
  val LayoutLevel(_, layout) = summary.levelFor(layoutScheme)

  // tile rdds to the same layout
  val rdd1 = RasterSourceRDD.tiledLayerRDD(source1, layout, KeyExtractor.spatialKeyExtractor, rasterSummary = Some(summary))
  val rdd2 = RasterSourceRDD.tiledLayerRDD(source2, layout, KeyExtractor.spatialKeyExtractor, rasterSummary = Some(summary))

  // merge
  val rdd = rdd1.merge(rdd2)

  // regrid
  rdd.regrid(1024).toGeoTiffs().foreach {
    case (key, mTile) =>
      val localPath = s"/Users/.../Downloads/merge_$key.tif"
      MultibandGeoTiff(mTile.tile, mTile.extent, mTile.crs).write(localPath, optimizedOrder = true)
  }
}
```

**Comment by imperio-wxm** [comment]
@pomadchin Hi, if I want to recalculate the keys and re-layout, is there any API or code I can refer to?

**Comment by pomadchin** [comment]
hey @imperio-wxm, I am afraid no. I think you want smth like `tileToLayout` but for any `TileLayerRDD` which is not implemented.

**Comment by pomadchin** [comment]
I'm closing this for now, feel free to reopen it / create a new issue!
