### ISSUE TITLE
java.io.InvalidClassException: geotrellis.layer.TileLayerMetadata; local class incompatible: stream classdesc serialVersionUID = 3142813742075090433, local class serialVersionUID = -468075711590230574

### ISSUE THREAD

**Issue by CaiCaiXian** [locationtech/geotrellis#3519]
## Describe the bug

Caused by: java.io.InvalidClassException: geotrellis.layer.TileLayerMetadata; local class incompatible: stream classdesc serialVersionUID = 3142813742075090433, local class serialVersionUID = -468075711590230574
        at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:699)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2005)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1852)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2186)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
        at scala.collection.immutable.List$SerializationProxy.readObject(List.scala:527)
        at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1184)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2322)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2431)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2355)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2213)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1669)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:503)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:461)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:85)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
        at org.apache.spark.scheduler.Task.run(Task.scala:136)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

## To Reproduce

  def pyramid(inputPath:String,outputPath:String,targetCRSCode:Int,tileFormat:String,serverFormat:String)(implicit sc:SparkContext): Unit ={
    if (StrUtil.isBlankIfStr(inputPath)||StrUtil.isBlankIfStr(outputPath)){
      println(inputPath)
      println(outputPath)
      throw new IllegalArgumentException("path error")
    }
    val formatInputPath = SparkFileUtil.correctPath(SparkFileUtil.getFormatPath(inputPath))
    val formatOutputPath = SparkFileUtil.correctPath(SparkFileUtil.getFormatPath(outputPath))

    val layerName = FileUtil.getPrefix(new File(formatInputPath))
    val inputRDD:RDD[(ProjectedExtent, MultibandTile)] = sc.hadoopMultibandGeoTiffRDD(formatInputPath)
  
    val (_, rasterMetaData) = CollectTileLayerMetadata.fromRDD(inputRDD, FloatingLayoutScheme(512))
  
    val tiledRDD: RDD[(SpatialKey, MultibandTile)] =
      inputRDD
         .tileToLayout(rasterMetaData.cellType, rasterMetaData.layout, Bilinear)
        .repartition(100)

    val targetCRS = CRS.fromEpsgCode(targetCRSCode);
    val layoutScheme = ZoomedLayoutScheme(targetCRS, tileSize = 256)

    //val reprojected: ProjectedExtentComponentReprojectMethods[ProjectedExtent, MultibandTile] = new TileRDDReprojectMethods(tiledRDD)
    //val reprojectedRDD: RDD[(ProjectedExtent, MultibandTile)] = reprojected.reproject(WebMercator)
    val contextRDD = ContextRDD(tiledRDD,rasterMetaData)
    val reprojected: TileRDDReprojectMethods[SpatialKey, MultibandTile] = new TileRDDReprojectMethods(contextRDD)
    val (zoom,reprojectedRDD): (Int, RDD[(SpatialKey, MultibandTile)] with Metadata[TileLayerMetadata[SpatialKey]]) = reprojected.reproject(targetCRS, layoutScheme)

    val dirOutputPath = formatOutputPath + "/" + layerName
    val attributeStore = AttributeStore(dirOutputPath)

    val writer = LayerWriter(dirOutputPath)

    Pyramid.upLevels(reprojectedRDD, layoutScheme, zoom, Bilinear) { (rdd, z) =>

      val layerId = LayerId(layerName, z)

      if(attributeStore.layerExists(layerId)) {
        attributeStore match {
          case store: HadoopAttributeStore =>
            new HadoopLayerManager(store).delete(layerId)
          case store: FileAttributeStore =>
            new FileLayerManager(store).delete(layerId)
        }
      }
     
      writer.write(layerId, rdd, ZCurveKeyIndexMethod)

    }

    translateImage(dirOutputPath,layerName,tileFormat,serverFormat)
  }

## Expected behavior
the code run well in local spark but failled in the remote spark which deployed by docker
when i write rdd to hdfs ,it happened. code : writer.write(layerId, rdd, ZCurveKeyIndexMethod)

## Environment

- Java version: 1.8
- Scala version: 2.12.17
- GeoTrellis version: 3.7.0

## Additional context

The online answers all suggest that I should define a serialVersionUID  for this class, but I am unable to modify the code. how can i fixed the problem.

**Comment by pomadchin** [comment]
👋 Hello, check Scala and GeoTrellis versions within your project!

**Comment by pomadchin** [comment]
Oh right, it's a separate ticket for this discussion: https://github.com/locationtech/geotrellis/issues/3510

**Comment by pomadchin** [comment]
I'll close this tikcet for now; if there are any other question / issues feel free to reopen it / create new tickets!
